import TypePM.Elaboration
import TypePM.CanonicalCoercion
import TypePM.CertifiedInference

/-!
# Internal core reconstruction boundary

`Reconstruction.ExprDeriv` is the derivation-structured `Prop` certificate
produced by the certified inference pipeline without storing source-typing
premises as an oracle.  Its constructors mirror the coercion choices made by
inference, but Lean proof irrelevance means that this certificate is not itself
observable elaboration data.  This module gives that existing object its
role in the reconstruction architecture.  Successful inference
constructs core evidence, every such certificate factors into a recursively
reconstructed non-coercion head plus an explicit outer coercion plan, and
erasing either view recovers `RuntimeTyping`.  Outer plans are logically
normalizable through `Nonempty NormalPlan`; this does not yet make the inferred
plan observable data.

Pattern reconstruction inside this certificate keeps one raw expression and
parameter context across the entire pattern tree and threads raw bindings
left-to-right.  Value-pattern expressions, matcher arms, and clauses retain
their recursive reconstruction evidence, so the certificate does not fall
back to a `RuntimeTyping` oracle at those boundaries.

This is still a `Prop`-valued elaboration certificate, not an executable core
AST.  It is not another source-typing judgment.
-/

namespace TypePM
namespace Elaboration

open Inference.Reconstruction

/-- Provisional derivation-structured core certificate generated by reconstruction. -/
abbrev CoreTyping := Inference.Reconstruction.ExprDeriv

/-- One non-coercion root rule whose recursive premises all remain inside the
reconstruction certificate. -/
inductive CoreSynthHead (signature : FrozenSig) :
    NamedContext -> Expr -> Ty -> Prop where
  | var {context name scheme target} :
      context.find? name = some scheme ->
      scheme.ValueFlowInst target ->
      CoreSynthHead signature context (.var name) target
  | lam {context name body domain codomain} :
      CoreTyping signature ((name, NamedScheme.mono domain) :: context) body codomain ->
      CoreSynthHead signature context (.lam name body) (.fn domain codomain)
  | app {context function argument domain codomain} :
      CoreTyping signature context function (.fn domain codomain) ->
      CoreTyping signature context argument domain ->
      CoreSynthHead signature context (.app function argument) codomain
  | letE {context name value body valueTy bodyTy} :
      CoreTyping signature context value valueTy ->
      CoreTyping signature
        ((name, signature.generalize context valueTy) :: context) body bodyTy ->
      CoreSynthHead signature context (.letE name value body) bodyTy
  | fixE {context self argument body domain codomain} :
      self ≠ argument ->
      DirectSelf.Holds self body ->
      CoreTyping signature
        ((argument, NamedScheme.mono domain) ::
          (self, NamedScheme.mono (.fn domain codomain)) :: context)
        body codomain ->
      CoreSynthHead signature context (.fix self argument body)
        (.fn domain codomain)
  | lit {context value} :
      CoreSynthHead signature context (.lit value) .int
  | tuple {context expressions targets} :
      ExprsDeriv signature context expressions targets ->
      CoreSynthHead signature context (.tuple expressions) (.prod targets)
  | ctor {context name expressions targets result scheme} :
      signature.findDataCtor name = some scheme ->
      scheme.Inst targets result ->
      ExprsDeriv signature context expressions targets ->
      CoreSynthHead signature context (.ctor name expressions) result
  | prim {context op expressions targets result scheme} :
      signature.findPrimitive op = some scheme ->
      scheme.Inst targets result ->
      ExprsDeriv signature context expressions targets ->
      CoreSynthHead signature context (.prim op expressions) result
  | something {context target} :
      CoreSynthHead signature context .something (.matcher .any target)
  | matchAll
      {prevailing context target matcher pattern body targetTy patternCap
       bindings result} :
      CoreTyping signature context target targetTy ->
      ResolvedPatternDeriv signature prevailing context [] [] pattern
        patternCap targetTy bindings ->
      CoreTyping signature context matcher (.slot patternCap targetTy) ->
      CoreTyping signature (bindings.toContext ++ context) body result ->
      CoreSynthHead signature context (.matchAll target matcher pattern body)
        (Ty.listT result)
  | matcher {context clauses target capability evidence} :
      ResolvedClausesDeriv signature context clauses capability target evidence ->
      Shape.inferShape signature.observability evidence = some capability ->
      CatchAllLast clauses ->
      ArmExhaustive signature clauses target ->
      PPBindNodup clauses ->
      ArmBindNodup clauses ->
      CoverageOK signature.toMatcherSig clauses capability ->
      CoreSynthHead signature context (.matcher clauses)
        (.matcher capability target)

/-- A recursively reconstructed non-coercion head followed by one explicit
outer surface coercion plan. -/
inductive CoreCheck (signature : FrozenSig) (context : NamedContext)
    (expression : Expr) : Ty -> Prop where
  | intro {source target} :
      CoreSynthHead signature context expression source ->
      CoercionPlan signature context expression source target ->
      CoreCheck signature context expression target

/-- Reassemble a non-coercion core head into the existing reconstruction
certificate. -/
theorem CoreSynthHead.toCoreTyping
    {signature : FrozenSig} {context : NamedContext} {expression : Expr}
    {target : Ty}
    (typing : CoreSynthHead signature context expression target) :
    CoreTyping signature context expression target := by
  cases typing with
  | var lookup instanceTyping => exact .var lookup instanceTyping
  | lam bodyTyping => exact .lam bodyTyping
  | app functionTyping argumentTyping =>
      exact .app functionTyping argumentTyping
  | letE valueTyping bodyTyping => exact .letE valueTyping bodyTyping
  | fixE distinct direct bodyTyping =>
      exact .fixE distinct direct bodyTyping
  | lit => exact .lit
  | tuple expressionsTyping => exact .tuple expressionsTyping
  | ctor lookup instanceTyping expressionsTyping =>
      exact .ctor lookup instanceTyping expressionsTyping
  | prim lookup instanceTyping expressionsTyping =>
      exact .prim lookup instanceTyping expressionsTyping
  | something => exact .something
  | matchAll targetTyping patternTyping matcherTyping bodyTyping =>
      exact .matchAll targetTyping patternTyping matcherTyping bodyTyping
  | matcher clausesTyping shape catchAll exhaustive ppNodup armNodup coverage =>
      exact .matcher clausesTyping shape catchAll exhaustive ppNodup armNodup
        coverage

/-- Replay an explicit outer coercion plan on reconstruction evidence. -/
theorem CoercionPlan.toCoreTyping
    {signature : FrozenSig} {context : NamedContext} {expression : Expr}
    {source target : Ty}
    (plan : CoercionPlan signature context expression source target)
    (typing : CoreTyping signature context expression source) :
    CoreTyping signature context expression target := by
  induction plan with
  | refl => exact typing
  | matcherToSlot raw post =>
      exact .coerceMatcherToSlot typing raw post
  | checkSlotToSlot raw post =>
      exact .checkSlotToSlot typing raw post
  | productMatcher => exact .coerceProductMatcher typing (Subst.apply_id _)
  | slotTuple => exact .coerceSlotTuple typing (Subst.apply_id _)
  | trans _ _ firstIH secondIH => exact secondIH (firstIH typing)

/-- Reassemble a checked core head. -/
theorem CoreCheck.toCoreTyping
    {signature : FrozenSig} {context : NamedContext} {expression : Expr}
    {target : Ty}
    (checking : CoreCheck signature context expression target) :
    CoreTyping signature context expression target := by
  cases checking with
  | intro synthesis plan =>
      exact plan.toCoreTyping synthesis.toCoreTyping

/-- Erase explicit elaboration evidence back to `RuntimeTyping`. -/
theorem CoreTyping.erase
    {signature : FrozenSig} {context : NamedContext} {expression : Expr}
    {target : Ty}
    (typing : CoreTyping signature context expression target) :
    RuntimeTyping signature context expression target :=
  typing.toRuntimeTyping

/-- Erase a checked core-head factorization directly to `RuntimeTyping`. -/
theorem CoreCheck.erase
    {signature : FrozenSig} {context : NamedContext} {expression : Expr}
    {target : Ty}
    (checking : CoreCheck signature context expression target) :
    RuntimeTyping signature context expression target :=
  checking.toCoreTyping.erase

/-- Forget recursive reconstruction premises while retaining the same
non-coercion surface head. -/
theorem CoreSynthHead.toSynthHead
    {signature : FrozenSig} {context : NamedContext} {expression : Expr}
    {target : Ty}
    (typing : CoreSynthHead signature context expression target) :
    SynthHead signature context expression target := by
  cases typing with
  | var lookup instanceTyping => exact .var lookup instanceTyping
  | lam bodyTyping => exact .lam bodyTyping.erase
  | app functionTyping argumentTyping =>
      exact .app functionTyping.erase argumentTyping.erase
  | letE valueTyping bodyTyping =>
      exact .letE valueTyping.erase bodyTyping.erase
  | fixE distinct direct bodyTyping =>
      exact .fixE distinct direct bodyTyping.erase
  | lit => exact .lit
  | tuple expressionsTyping => exact .tuple expressionsTyping.toExprsTy
  | ctor lookup instanceTyping expressionsTyping =>
      exact .ctor lookup instanceTyping expressionsTyping.toExprsTy
  | prim lookup instanceTyping expressionsTyping =>
      exact .prim lookup instanceTyping expressionsTyping.toExprsTy
  | something => exact .something
  | matchAll targetTyping patternTyping matcherTyping bodyTyping =>
      exact .matchAll targetTyping.erase patternTyping.toResolvedPatternTy
        matcherTyping.erase bodyTyping.erase
  | matcher clausesTyping shape catchAll exhaustive ppNodup armNodup coverage =>
      exact .matcher clausesTyping.toResolvedClausesTy shape catchAll exhaustive
        ppNodup armNodup coverage

/-- Forget recursive core premises from a checked head. -/
theorem CoreCheck.toCheckHead
    {signature : FrozenSig} {context : NamedContext} {expression : Expr}
    {target : Ty}
    (checking : CoreCheck signature context expression target) :
    CheckHead signature context expression target := by
  cases checking with
  | intro synthesis plan =>
      exact ⟨_, synthesis.toSynthHead, plan⟩

/-- Every reconstruction certificate factors into a recursively reconstructed
non-coercion head followed by an explicit outer coercion plan. -/
theorem CoreTyping.toCoreCheck
    {signature : FrozenSig} {context : NamedContext} {expression : Expr}
    {target : Ty}
    (typing : CoreTyping signature context expression target) :
    CoreCheck signature context expression target := by
  apply ExprDeriv.rec
    (motive_1 := fun context expression target _ =>
      CoreCheck signature context expression target)
    (motive_2 := fun _ _ _ _ => True)
    (motive_3 := fun _ _ _ _ _ _ _ _ => True)
    (motive_4 := fun _ _ _ _ _ _ _ => True)
    (motive_5 := fun _ _ _ _ _ => True)
    (motive_6 := fun _ _ _ _ _ => True)
    (motive_7 := fun _ _ _ _ _ _ => True)
    (motive_8 := fun _ _ _ _ _ _ => True)
    (motive_9 := fun _ _ _ _ _ _ => True)
    (motive_10 := fun _ _ _ _ => True)
    (motive_11 := fun _ _ _ _ => True)
    (motive_12 := fun _ _ _ _ _ _ _ _ _ => True)
    (motive_13 := fun _ _ _ _ _ _ _ _ => True)
    (motive_14 := fun _ _ _ _ _ _ _ _ _ => True)
    (motive_15 := fun _ _ _ _ _ _ => True)
    (motive_16 := fun _ _ _ _ _ _ => True)
    (motive_17 := fun _ _ _ _ _ _ _ => True)
    (motive_18 := fun _ _ _ _ _ _ _ => True)
    (motive_19 := fun _ _ _ _ _ _ => True)
    (t := typing)
  all_goals intros
  all_goals
    first
    | trivial
    | (refine .intro ?_ .refl; constructor <;> assumption)
    | (rcases ‹CoreCheck signature _ _ _› with ⟨synthesis, plan⟩
       refine .intro synthesis (.trans plan ?_)
       first
       | exact .matcherToSlot (by assumption) (by assumption)
       | exact .checkSlotToSlot (by assumption) (by assumption)
       | exact .productMatcher
       | exact .slotTuple)

/-- The checked-head view is extensionally the existing recursive core
certificate. -/
theorem coreCheck_iff_coreTyping
    {signature : FrozenSig} {context : NamedContext} {expression : Expr}
    {target : Ty} :
    CoreCheck signature context expression target ↔
      CoreTyping signature context expression target :=
  ⟨CoreCheck.toCoreTyping, CoreTyping.toCoreCheck⟩

/-- Every recursive core certificate has a non-coercion head and a normalizable
outer plan.  The `Nonempty` wrapper records logical existence only; executable
plan data must still be produced directly by inference. -/
theorem CoreTyping.factorNormalHead
    {signature : FrozenSig} {context : NamedContext} {expression : Expr}
    {target : Ty}
    (typing : CoreTyping signature context expression target) :
    ∃ source,
      CoreSynthHead signature context expression source ∧
      Nonempty (CanonicalCoercion.NormalPlan signature context expression
        source target) := by
  cases typing.toCoreCheck with
  | intro synthesis plan =>
      exact ⟨_, synthesis, plan.normalizable⟩

/-- Soundness of a logically existing normal core-head factorization. -/
theorem normalHeadFactor_toCoreTyping
    {signature : FrozenSig} {context : NamedContext} {expression : Expr}
    {source target : Ty}
    (synthesis : CoreSynthHead signature context expression source)
    (normal : CanonicalCoercion.NormalPlan signature context expression
      source target) :
    CoreTyping signature context expression target :=
  normal.sound.toCoreTyping synthesis.toCoreTyping

/-- Logical normal-head factorization exactly characterizes the recursive core
certificate. -/
theorem coreTyping_iff_normalHeadFactor
    {signature : FrozenSig} {context : NamedContext} {expression : Expr}
    {target : Ty} :
    CoreTyping signature context expression target ↔
      ∃ source,
        CoreSynthHead signature context expression source ∧
        Nonempty (CanonicalCoercion.NormalPlan signature context expression
          source target) := by
  constructor
  · exact CoreTyping.factorNormalHead
  · rintro ⟨source, synthesis, ⟨normal⟩⟩
    exact normalHeadFactor_toCoreTyping synthesis normal

/-- Successful public inference constructs an explicit core typing, before
the final forgetful map used by surface soundness. -/
theorem infer_success_core
    {signature : FrozenSig} {context : NamedContext} {expression : Expr}
    {result : Inference.ExprResult}
    (success : Inference.infer signature context expression = some result) :
    CoreTyping signature
      (Inference.ResolvedContext result.state.prevailing context)
      expression result.resolvedTarget :=
  Inference.infer_success_reconstruct success

/-- Successful public inference also exposes the recursively reconstructed
head and its explicit outer coercion spine. -/
theorem infer_success_core_check
    {signature : FrozenSig} {context : NamedContext} {expression : Expr}
    {result : Inference.ExprResult}
    (success : Inference.infer signature context expression = some result) :
    CoreCheck signature
      (Inference.ResolvedContext result.state.prevailing context)
      expression result.resolvedTarget :=
  (infer_success_core success).toCoreCheck

/-- Successful inference has a logically normalizable outer coercion factor. -/
theorem infer_success_normal_core_factor
    {signature : FrozenSig} {context : NamedContext} {expression : Expr}
    {result : Inference.ExprResult}
    (success : Inference.infer signature context expression = some result) :
    ∃ source,
      CoreSynthHead signature
        (Inference.ResolvedContext result.state.prevailing context)
        expression source ∧
      Nonempty (CanonicalCoercion.NormalPlan signature
        (Inference.ResolvedContext result.state.prevailing context)
        expression source result.resolvedTarget) :=
  (infer_success_core success).factorNormalHead

/-- Surface soundness factors through the explicit core evidence. -/
theorem infer_success_runtimeTyping_via_core
    {signature : FrozenSig} {context : NamedContext} {expression : Expr}
    {result : Inference.ExprResult}
    (success : Inference.infer signature context expression = some result) :
    RuntimeTyping signature
      (Inference.ResolvedContext result.state.prevailing context)
      expression result.resolvedTarget :=
  (infer_success_core success).erase

end Elaboration
end TypePM
