import TypePM.Elaboration
import TypePM.CertifiedInference

/-!
# Public core-typing boundary

`Reconstruction.ExprDeriv` is the proof-relevant typing tree produced by the
certified inference pipeline without storing source-typing premises as an
oracle.  Both it and surface `HasTy` expose coercion rules in their proof
objects; the distinction is that the source program omits those coercions
whereas reconstruction records the choices made by inference.  This module
gives that existing object its provisional role in the surface/core
architecture and records the two public bridges: successful inference
constructs core evidence, and erasing the evidence recovers surface typing.

This is still a `Prop`-valued elaboration certificate, not an executable core
AST.  Principality and completeness are deliberately separate future
theorems.  In particular, naming this already-certified evidence does not
weaken or hide the surface counterexample.
-/

namespace TypePM
namespace Elaboration

/-- Provisional proof-relevant core certificate generated by reconstruction. -/
abbrev CoreTyping := Inference.Reconstruction.ExprDeriv

/-- Erase explicit elaboration evidence back to the surface typing relation. -/
theorem CoreTyping.erase
    {signature : FrozenSig} {context : Context} {expression : Expr}
    {target : Ty}
    (typing : CoreTyping signature context expression target) :
    HasTy signature context expression target :=
  typing.toHasTy

/-- Successful public inference constructs an explicit core typing, before
the final forgetful map used by surface soundness. -/
theorem infer_success_core
    {signature : FrozenSig} {context : Context} {expression : Expr}
    {result : Inference.ExprResult}
    (success : Inference.infer signature context expression = some result) :
    CoreTyping signature
      (Inference.ResolvedContext result.state.prevailing context)
      expression result.resolvedTarget :=
  Inference.infer_success_reconstruct success

/-- Surface soundness factors through the explicit core evidence. -/
theorem infer_success_surface_via_core
    {signature : FrozenSig} {context : Context} {expression : Expr}
    {result : Inference.ExprResult}
    (success : Inference.infer signature context expression = some result) :
    HasTy signature
      (Inference.ResolvedContext result.state.prevailing context)
      expression result.resolvedTarget :=
  (infer_success_core success).erase

end Elaboration
end TypePM
