import TypePM.DemandTypingInferenceCompletenessValidatorAudit

/-!
# Open validator coverage for traversal completeness

The ordinary terminal-validator clauses are stable in a slightly stronger
form than their final root statement suggests.  A traversal prefix may retain
proofs for all of its events *at every future history cut*.  This open form is
the compositional invariant needed by the completeness recursion: solver-only
steps merely advance the prefix, while an event emitter proves one local
clause for every later terminal cut.

The three audit-sensitive events remain separate.  Their witnesses contain
facts from `DDSynthTerminalAudit`, so they must be accumulated by the
origin-and-audit recursion through `TerminalAuditEventCoverage`; executable
success alone supplies only the ordinary coverage defined here.
-/

namespace TypePM
namespace Inference
namespace Reconstruction

/-- The seven validator obligations generated by ordinary executable
traversal.  The four fields in `traversal` cover allocation, canonical
instances, and expected-slot alignment; the remaining two fields cover the
ordinary and dual alignment traces. -/
structure OrdinaryValidatorEventCondition
    (signature : FrozenSig) (terminal : InferState)
    (event : TraceEvent) : Prop where
  traversal : TraversalValidatorEventCondition signature terminal event
  typeAlignment : TypeAlignmentEventCondition terminal event
  dualAlignment : DualAlignmentEventCondition terminal event

/-- A successful ordinary type-alignment emitter supplies the complete local
ordinary-validator condition for its recorded event at every later cut. -/
theorem alignTypes_ordinaryValidatorEventCondition
    {signature : FrozenSig} {state aligned terminal : InferState}
    {origin : ConstraintOrigin} {left right : Ty}
    (success : alignTypes state origin left right = some aligned)
    (suffix : aligned.HistoryPrefix terminal) :
    OrdinaryValidatorEventCondition signature terminal
      (.typeAlignment state.trace.solves.length aligned.trace.solves.length
        left right (state.prevailing.apply left)
        (state.prevailing.apply right)) := by
  refine
    { traversal := ?_
      typeAlignment :=
        alignTypes_typeAlignmentEventCondition success suffix
      dualAlignment := trivial }
  exact
    { primitiveHole := ⟨trivial⟩
      patternLeaf := ⟨trivial⟩
      canonicalInstance := ⟨trivial⟩
      slot := ⟨trivial⟩ }

/-- Dual counterpart of `alignTypes_ordinaryValidatorEventCondition`. -/
theorem alignDuals_ordinaryValidatorEventCondition
    {signature : FrozenSig} {state aligned terminal : InferState}
    {origin : ConstraintOrigin} {left right : Dual}
    (success : alignDuals state origin left right = some aligned)
    (suffix : aligned.HistoryPrefix terminal) :
    OrdinaryValidatorEventCondition signature terminal
      (.dualAlignment state.trace.solves.length aligned.trace.solves.length
        left right (left.applySubst state.prevailing)
        (right.applySubst state.prevailing)) := by
  refine
    { traversal := ?_
      typeAlignment := trivial
      dualAlignment :=
        alignDuals_dualAlignmentEventCondition success suffix }
  exact
    { primitiveHole := ⟨trivial⟩
      patternLeaf := ⟨trivial⟩
      canonicalInstance := ⟨trivial⟩
      slot := ⟨trivial⟩ }

/-- Prefix-open coverage: every event already emitted by `prefix` satisfies
its ordinary validator obligations at every future append-only history cut.

Quantifying over the future terminal is essential.  Instance, slot, and
alignment conditions mention the terminal substitution, so they cannot in
general be transported from a proof stated only at the current prefix. -/
def OpenOrdinaryValidatorEventCoverage
    (signature : FrozenSig) (initial : InferState) : Prop :=
  ∀ terminal, initial.HistoryPrefix terminal →
    ∀ event, event ∈ initial.trace.events →
      OrdinaryValidatorEventCondition signature terminal event

/-- Empty inference history has open ordinary coverage. -/
theorem OpenOrdinaryValidatorEventCoverage.empty
    (signature : FrozenSig) (supply : InferenceBase.FreshSupply) :
    OpenOrdinaryValidatorEventCoverage signature (InferState.empty supply) := by
  intro terminal history event membership
  simp [InferState.empty] at membership

/-- At the root terminal cut, open coverage yields exactly the three ordinary
coverage packages consumed by validator completeness. -/
theorem OpenOrdinaryValidatorEventCoverage.atTerminal
    {signature : FrozenSig} {state : InferState}
    (coverage : OpenOrdinaryValidatorEventCoverage signature state) :
    TraversalValidatorEventCoverage signature state ∧
      TraceTypeAlignmentConditions state ∧
      TraceDualAlignmentConditions state := by
  have terminal := coverage state (InferState.HistoryPrefix.refl state)
  refine ⟨?_, ?_, ?_⟩
  · intro event membership
    exact (terminal event membership).traversal
  · rw [traceTypeAlignmentConditions_iff_eventCoverage]
    intro event membership
    exact (terminal event membership).typeAlignment
  · rw [traceDualAlignmentConditions_iff_eventCoverage]
    intro event membership
    exact (terminal event membership).dualAlignment

/-- Extend an open prefix through an arbitrary successful append-only run.
Only genuinely new event values need local justification; an appended event
equal to an older event is already covered by the older witness. -/
theorem OpenOrdinaryValidatorEventCoverage.transportExtension
    {signature : FrozenSig} {earlier later : InferState}
    (before : OpenOrdinaryValidatorEventCoverage signature earlier)
    (history : earlier.HistoryPrefix later)
    (newEvents : ∀ event,
      event ∈ later.trace.events → event ∉ earlier.trace.events →
      ∀ terminal, later.HistoryPrefix terminal →
        OrdinaryValidatorEventCondition signature terminal event) :
    OpenOrdinaryValidatorEventCoverage signature later := by
  intro terminal suffix event membership
  by_cases previous : event ∈ earlier.trace.events
  · exact before terminal (history.trans suffix) event previous
  · exact newEvents event membership previous terminal suffix

/-- Solver/allocation updates that emit no event transport open coverage
without any additional semantic premise. -/
theorem OpenOrdinaryValidatorEventCoverage.transportNoEvents
    {signature : FrozenSig} {earlier later : InferState}
    (before : OpenOrdinaryValidatorEventCoverage signature earlier)
    (history : earlier.HistoryPrefix later)
    (eventsEq : later.trace.events = earlier.trace.events) :
    OpenOrdinaryValidatorEventCoverage signature later := by
  apply before.transportExtension history
  intro event membership previous
  exfalso
  apply previous
  simpa [eventsEq] using membership

/-- Append one locally justified event.  The local premise is deliberately
future-open, matching the emitter lemmas for type, dual, instance, and slot
events. -/
theorem OpenOrdinaryValidatorEventCoverage.recordEvent
    {signature : FrozenSig} {state : InferState} {event : TraceEvent}
    (before : OpenOrdinaryValidatorEventCoverage signature state)
    (latest : ∀ terminal,
      (state.recordEvent event).HistoryPrefix terminal →
        OrdinaryValidatorEventCondition signature terminal event) :
    OpenOrdinaryValidatorEventCoverage signature
      (state.recordEvent event) := by
  intro terminal suffix candidate membership
  simp only [InferState.recordEvent, List.mem_append,
    List.mem_singleton] at membership
  rcases membership with previous | newest
  · exact before terminal
      ((state.historyPrefix_recordEvent event).trans suffix)
      candidate previous
  · subst candidate
    exact latest terminal suffix

/-- Bundle the two independent recursion products needed at the final root:
ordinary coverage from executable traversal and sensitive coverage from the
terminal-audited origin recursion. -/
structure RootValidatorEventCoverage
    (terminal : Subst) (signature : FrozenSig) (state : InferState) : Prop where
  ordinary : OpenOrdinaryValidatorEventCoverage signature state
  sensitive : TerminalAuditEventCoverage terminal signature state

/-- The combined root certificate projects to the four premises used by the
existing validator assembly theorem. -/
theorem RootValidatorEventCoverage.atTerminal
    {terminal : Subst} {signature : FrozenSig} {state : InferState}
    (coverage : RootValidatorEventCoverage terminal signature state) :
    TraversalValidatorEventCoverage signature state ∧
      TerminalAuditEventCoverage terminal signature state ∧
      TraceTypeAlignmentConditions state ∧
      TraceDualAlignmentConditions state := by
  obtain ⟨traversal, types, duals⟩ := coverage.ordinary.atTerminal
  exact ⟨traversal, coverage.sensitive, types, duals⟩

end Reconstruction
end Inference
end TypePM
