import TypePM.DemandTypingInferenceCompletenessValidatorAudit

/-!
# Open validator coverage for traversal completeness

The ordinary terminal-validator clauses are stable in a slightly stronger
form than their final root statement suggests.  A traversal prefix may retain
proofs for all of its events *at every future history cut*.  This open form is
the compositional invariant needed by the completeness recursion: solver-only
steps merely advance the prefix, while an event emitter proves one local
clause for every later terminal cut.

The three audit-sensitive events remain separate.  Their witnesses contain
facts from `DemandSynthTerminalAudit`, so they must be accumulated by the
origin-and-audit recursion through `TerminalAuditEventCoverage`; executable
success alone supplies only the ordinary coverage defined here.
-/

namespace TypePM
namespace Inference
namespace Reconstruction

/-- The seven validator obligations generated by ordinary executable
traversal.  The four fields in `traversal` cover allocation, canonical
instances, and expected-slot alignment; the remaining two fields cover the
ordinary and dual alignment traces. -/
structure OrdinaryValidatorEventCondition
    (signature : FrozenSig) (terminal : InferState)
    (event : TraceEvent) : Prop where
  traversal : TraversalValidatorEventCondition signature terminal event
  typeAlignment : TypeAlignmentEventCondition terminal event
  dualAlignment : DualAlignmentEventCondition terminal event

/-- Assemble one ordinary event from the three independent validator folds. -/
theorem OrdinaryValidatorEventCondition.mkOfConditions
    {signature : FrozenSig} {terminal : InferState} {event : TraceEvent}
    (traversal : TraversalValidatorEventCondition signature terminal event)
    (types : TypeAlignmentEventCondition terminal event)
    (duals : DualAlignmentEventCondition terminal event) :
    OrdinaryValidatorEventCondition signature terminal event :=
  ⟨traversal, types, duals⟩

/-- A successful ordinary type-alignment emitter supplies the complete local
ordinary-validator condition for its recorded event at every later cut. -/
theorem alignTypes_ordinaryValidatorEventCondition
    {signature : FrozenSig} {state aligned terminal : InferState}
    {origin : ConstraintOrigin} {left right : Ty}
    (success : alignTypes state origin left right = some aligned)
    (suffix : aligned.HistoryPrefix terminal) :
    OrdinaryValidatorEventCondition signature terminal
      (.typeAlignment state.trace.solves.length aligned.trace.solves.length
        left right (state.prevailing.apply left)
        (state.prevailing.apply right)) := by
  refine
    { traversal := ?_
      typeAlignment :=
        alignTypes_typeAlignmentEventCondition success suffix
      dualAlignment := trivial }
  exact
    { primitiveHole := ⟨trivial⟩
      patternLeaf := ⟨trivial⟩
      canonicalInstance := ⟨trivial⟩
      slot := ⟨trivial⟩ }

/-- Dual counterpart of `alignTypes_ordinaryValidatorEventCondition`. -/
theorem alignDuals_ordinaryValidatorEventCondition
    {signature : FrozenSig} {state aligned terminal : InferState}
    {origin : ConstraintOrigin} {left right : Dual}
    (success : alignDuals state origin left right = some aligned)
    (suffix : aligned.HistoryPrefix terminal) :
    OrdinaryValidatorEventCondition signature terminal
      (.dualAlignment state.trace.solves.length aligned.trace.solves.length
        left right (left.applySubst state.prevailing)
        (right.applySubst state.prevailing)) := by
  refine
    { traversal := ?_
      typeAlignment := trivial
      dualAlignment :=
        alignDuals_dualAlignmentEventCondition success suffix }
  exact
    { primitiveHole := ⟨trivial⟩
      patternLeaf := ⟨trivial⟩
      canonicalInstance := ⟨trivial⟩
      slot := ⟨trivial⟩ }

/-- A successful expected-type check supplies the exact canonical slot event
condition at every later cut. -/
theorem alignExprResultAtExpected_ordinaryValidatorEventCondition
    {signature : FrozenSig} {path : SyntaxPath}
    {expressionResult : ExprResult} {expected : Ty}
    {final terminal : InferState}
    (success : alignExprResultAtExpected path expressionResult expected =
      some final)
    (suffix : final.HistoryPrefix terminal) :
    OrdinaryValidatorEventCondition signature terminal (.slotAlignment
      expressionResult.state.trace.solves.length final.trace.solves.length
      (match expectedCoercionPlan expressionResult.state
          expressionResult.target expected with
        | .productMatcherLift duals => productMatcherTarget duals
        | .slotTupleLift duals => slotTupleTarget duals
        | .raw => expressionResult.state.prevailing.apply
            expressionResult.target)
      (expressionResult.state.prevailing.apply expected)) := by
  have canonical :=
    alignExprResultAtExpected_canonicalSlotEventCondition success suffix
  refine
    { traversal := ?_
      typeAlignment := trivial
      dualAlignment := trivial }
  exact instanceEventCondition (by trivial) (by trivial) (by trivial)
    canonical

/-- Closed constructor instantiation contributes a canonical instance event
at every later terminal cut. -/
theorem ctorInstantiation_ordinaryValidatorEventCondition
    {signature : FrozenSig} {terminal : InferState} {solveCount : Nat}
    {supply : InferenceBase.FreshSupply} {scheme : CtorScheme}
    (closed : scheme.Closed)
    (solveBound : solveCount ≤ terminal.trace.solves.length) :
    OrdinaryValidatorEventCondition signature terminal
      (.ctorInstantiation solveCount supply scheme
        (InferenceBase.instantiateCtorScheme supply scheme).value.1
        (InferenceBase.instantiateCtorScheme supply scheme).value.2
        (freshCapImages supply scheme.capBinders)) := by
  refine
    { traversal := ?_
      typeAlignment := trivial
      dualAlignment := trivial }
  exact instanceEventCondition (by trivial) (by trivial)
    (ctorInstanceEventCondition_atTerminal closed solveBound) (by trivial)

/-- Context-scheme instantiation adapter.  The lookup equation is supplied at
the terminal cut by the context-bisimulation component of the completeness
recursion; protected canonical images discharge the remaining witness. -/
theorem schemeInstantiation_ordinaryValidatorEventCondition
    {signature : FrozenSig} {terminal : InferState} {solveCount : Nat}
    {supply : InferenceBase.FreshSupply} {scheme : Scheme}
    {name : String} {rawContext context : Context}
    {fixedCaps reservedCaps : List CapVar}
    {fixedTys reservedTys : List TypePM.TyVar}
    (solveBound : solveCount ≤ terminal.trace.solves.length)
    (terminalLookup :
      (rawContext.applySubst terminal.prevailing).find? name =
        some (scheme.applyMeta terminal.prevailing))
    (producerSafe : ProtectedProducerTrace terminal)
    (freshProtected : ∀ image,
      image ∈ Scheme.canonicalCapImages supply scheme →
        image ∈ terminal.protectedCaps) :
    OrdinaryValidatorEventCondition signature terminal
      (.schemeInstantiation solveCount supply scheme name rawContext context
        fixedCaps fixedTys reservedCaps reservedTys
        (InferenceBase.instantiateScheme supply scheme).value
        (Scheme.canonicalCapImages supply scheme)
        (Scheme.canonicalTyImages supply scheme)) := by
  refine
    { traversal := ?_
      typeAlignment := trivial
      dualAlignment := trivial }
  exact instanceEventCondition (by trivial) (by trivial)
    (schemeInstanceEventCondition_atTerminal solveBound terminalLookup
      producerSafe freshProtected) (by trivial)

/-- Closed dual-scheme instantiation adapter. -/
theorem dualInstantiation_ordinaryValidatorEventCondition
    {signature : FrozenSig} {terminal : InferState} {solveCount : Nat}
    {supply : InferenceBase.FreshSupply} {scheme : DualScheme}
    {rawContext : Context} {rawParameters : PatternCtx}
    {rawBindings : MonoCtx} {context : Context}
    {parameters : PatternCtx} {bindings : MonoCtx}
    {fixedCaps reservedCaps : List CapVar}
    {fixedTys reservedTys : List TypePM.TyVar}
    (closed : scheme.Closed)
    (solveBound : solveCount ≤ terminal.trace.solves.length)
    (producerSafe : ProtectedProducerTrace terminal)
    (freshProtected : ∀ image,
      image ∈ freshCapImages supply scheme.capBinders →
        image ∈ terminal.protectedCaps) :
    OrdinaryValidatorEventCondition signature terminal
      (.dualInstantiation solveCount supply scheme rawContext rawParameters
        rawBindings context parameters bindings fixedCaps fixedTys
        reservedCaps reservedTys
        (InferenceBase.instantiateDualScheme supply scheme).value.1
        (InferenceBase.instantiateDualScheme supply scheme).value.2
        (freshCapImages supply scheme.capBinders)
        (freshTyImages supply scheme.tyBinders)) := by
  refine
    { traversal := ?_
      typeAlignment := trivial
      dualAlignment := trivial }
  exact instanceEventCondition (by trivial) (by trivial)
    (dualInstanceEventCondition_atTerminal closed solveBound producerSafe
      freshProtected) (by trivial)

/-! ## Validator-neutral events -/

/-- Events which contribute no nontrivial clause to any ordinary validator
fold.  Keeping this whitelist explicit ensures that adding a new trace event
cannot silently classify it as validator neutral. -/
inductive ValidatorNeutralEvent : TraceEvent → Prop where
  | visit (kind path) : ValidatorNeutralEvent (.visit kind path)
  | freshCap (origin varId) : ValidatorNeutralEvent (.freshCap origin varId)
  | freshTy (origin varId) : ValidatorNeutralEvent (.freshTy origin varId)
  | fixPlaceholder (self argument target path) :
      ValidatorNeutralEvent (.fixPlaceholder self argument target path)
  | directSelfAccepted (self target path) :
      ValidatorNeutralEvent (.directSelfAccepted self target path)
  | directSelfReference (self target path) :
      ValidatorNeutralEvent (.directSelfReference self target path)
  | actualClauseEvidence (clause holes evidence) :
      ValidatorNeutralEvent (.actualClauseEvidence clause holes evidence)
  | literalCoverage (clauses capability) :
      ValidatorNeutralEvent (.literalCoverage clauses capability)
  | capabilityFlow (tag evidence) :
      ValidatorNeutralEvent (.capabilityFlow tag evidence)
  | inferredExpr (expression target path) :
      ValidatorNeutralEvent (.inferredExpr expression target path)
  | inferredPattern (pattern dual bindings path) :
      ValidatorNeutralEvent (.inferredPattern pattern dual bindings path)
  | inferredPPatWild (target holes bindings path) :
      ValidatorNeutralEvent (.inferredPPat .wild target holes bindings path)
  | inferredPPatValue (name target holes bindings path) :
      ValidatorNeutralEvent
        (.inferredPPat (.pval name) target holes bindings path)
  | inferredPPatCtor (name patterns target holes bindings path) :
      ValidatorNeutralEvent
        (.inferredPPat (.ctor name patterns) target holes bindings path)
  | inferredPPatTuple (patterns target holes bindings path) :
      ValidatorNeutralEvent
        (.inferredPPat (.tuple patterns) target holes bindings path)
  | inferredDPat (pattern target bindings path) :
      ValidatorNeutralEvent (.inferredDPat pattern target bindings path)
  | capabilityExportFreeze (solveCount images raw localTarget surviving) :
      ValidatorNeutralEvent
        (.capabilityExportFreeze solveCount images raw localTarget surviving)

/-- A whitelisted neutral event satisfies all ordinary clauses at every
terminal state. -/
theorem ValidatorNeutralEvent.ordinaryCondition
    {event : TraceEvent} (neutral : ValidatorNeutralEvent event)
    (signature : FrozenSig) (terminal : InferState) :
    OrdinaryValidatorEventCondition signature terminal event := by
  cases neutral <;>
    refine
      { traversal := ?_
        typeAlignment := trivial
        dualAlignment := trivial } <;>
    exact
      { primitiveHole := ⟨by simp [PrimitiveHoleEventCondition]⟩
        patternLeaf := ⟨by simp [PatternLeafEventCondition]⟩
        canonicalInstance := ⟨by simp [CanonicalInstanceEventCondition]⟩
        slot := ⟨by simp [CanonicalSlotEventCondition]⟩ }

/-! ## Fresh-allocation event adapters -/

/-- The primitive-hole freshness fact is state independent once allocated,
so the emission-cut proof can be reused at every future terminal. -/
theorem primitiveHole_ordinaryValidatorEventCondition
    {signature : FrozenSig} {allocation terminal : InferState}
    {path : SyntaxPath} {target : Ty}
    (signatureBelow : InferenceBase.CapVarsBelow allocation.supply
      signature.capVars)
    (targetBounded : target.BoundedBy allocation.supply) :
    OrdinaryValidatorEventCondition signature terminal
      (.inferredPPat .hole target
        [⟨.var ⟨allocation.supply.nextCap⟩, target⟩] [] path) := by
  have emitted := primitiveHoleEventCondition
    (state := allocation) (path := path) signatureBelow targetBounded
  refine
    { traversal := ?_
      typeAlignment := trivial
      dualAlignment := trivial }
  exact
    { primitiveHole := emitted.primitiveHole
      patternLeaf := emitted.patternLeaf
      canonicalInstance := ⟨by trivial⟩
      slot := ⟨by trivial⟩ }

/-- Pattern-variable allocation adapter for arbitrary future terminals. -/
theorem patternVar_ordinaryValidatorEventCondition
    {signature : FrozenSig} {allocation terminal : InferState}
    {context : Context} {parameters : PatternCtx} {bindings : MonoCtx}
    (signatureCaps : InferenceBase.CapVarsBelow allocation.supply
      signature.capVars)
    (contextCaps : InferenceBase.CapVarsBelow allocation.supply context.fcv)
    (parameterCaps : InferenceBase.CapVarsBelow allocation.supply
      parameters.fcv)
    (bindingCaps : InferenceBase.CapVarsBelow allocation.supply bindings.fcv)
    (signatureTys : InferenceBase.TyVarsBelow allocation.supply
      signature.tyVars)
    (contextTys : InferenceBase.TyVarsBelow allocation.supply context.ftv)
    (parameterTys : InferenceBase.TyVarsBelow allocation.supply parameters.ftv)
    (bindingTys : InferenceBase.TyVarsBelow allocation.supply bindings.ftv) :
    OrdinaryValidatorEventCondition signature terminal
      (.patternVarFresh context parameters bindings
        ⟨allocation.supply.nextCap⟩ allocation.supply.nextTy) := by
  have emitted := patternVarEventCondition (state := allocation)
    signatureCaps contextCaps parameterCaps bindingCaps signatureTys contextTys
    parameterTys bindingTys
  refine
    { traversal := ?_
      typeAlignment := trivial
      dualAlignment := trivial }
  exact
    { primitiveHole := emitted.primitiveHole
      patternLeaf := emitted.patternLeaf
      canonicalInstance := ⟨by trivial⟩
      slot := ⟨by trivial⟩ }

/-- Pattern-wildcard allocation adapter for arbitrary future terminals. -/
theorem patternWild_ordinaryValidatorEventCondition
    {signature : FrozenSig} {allocation terminal : InferState}
    {context : Context} {parameters : PatternCtx} {bindings : MonoCtx}
    (signatureCaps : InferenceBase.CapVarsBelow allocation.supply
      signature.capVars)
    (contextCaps : InferenceBase.CapVarsBelow allocation.supply context.fcv)
    (parameterCaps : InferenceBase.CapVarsBelow allocation.supply
      parameters.fcv)
    (bindingCaps : InferenceBase.CapVarsBelow allocation.supply bindings.fcv)
    (signatureTys : InferenceBase.TyVarsBelow allocation.supply
      signature.tyVars)
    (contextTys : InferenceBase.TyVarsBelow allocation.supply context.ftv)
    (parameterTys : InferenceBase.TyVarsBelow allocation.supply parameters.ftv)
    (bindingTys : InferenceBase.TyVarsBelow allocation.supply bindings.ftv) :
    OrdinaryValidatorEventCondition signature terminal
      (.patternWildFresh context parameters bindings
        ⟨allocation.supply.nextCap⟩ allocation.supply.nextTy) := by
  have emitted := patternWildEventCondition (state := allocation)
    signatureCaps contextCaps parameterCaps bindingCaps signatureTys contextTys
    parameterTys bindingTys
  refine
    { traversal := ?_
      typeAlignment := trivial
      dualAlignment := trivial }
  exact
    { primitiveHole := emitted.primitiveHole
      patternLeaf := emitted.patternLeaf
      canonicalInstance := ⟨by trivial⟩
      slot := ⟨by trivial⟩ }

/-- Value-pattern capability allocation adapter for arbitrary future cuts. -/
theorem patternValue_ordinaryValidatorEventCondition
    {signature : FrozenSig} {allocation terminal : InferState}
    {context : Context} {parameters : PatternCtx} {bindings : MonoCtx}
    {target : Ty}
    (signatureCaps : InferenceBase.CapVarsBelow allocation.supply
      signature.capVars)
    (contextCaps : InferenceBase.CapVarsBelow allocation.supply context.fcv)
    (parameterCaps : InferenceBase.CapVarsBelow allocation.supply
      parameters.fcv)
    (bindingCaps : InferenceBase.CapVarsBelow allocation.supply bindings.fcv)
    (targetBounded : target.BoundedBy allocation.supply) :
    OrdinaryValidatorEventCondition signature terminal
      (.patternValueFresh context parameters bindings
        ⟨allocation.supply.nextCap⟩ target) := by
  have emitted := patternValueEventCondition (state := allocation)
    signatureCaps contextCaps parameterCaps bindingCaps targetBounded
  refine
    { traversal := ?_
      typeAlignment := trivial
      dualAlignment := trivial }
  exact
    { primitiveHole := emitted.primitiveHole
      patternLeaf := emitted.patternLeaf
      canonicalInstance := ⟨by trivial⟩
      slot := ⟨by trivial⟩ }

/-- Prefix-open coverage: every event already emitted by `prefix` satisfies
its ordinary validator obligations at every future append-only history cut.

Quantifying over the future terminal is essential.  Instance, slot, and
alignment conditions mention the terminal substitution, so they cannot in
general be transported from a proof stated only at the current prefix. -/
def OpenOrdinaryValidatorEventCoverage
    (signature : FrozenSig) (initial : InferState) : Prop :=
  ∀ terminal, initial.StateExtension terminal →
    ProtectedProducerTrace terminal →
    ∀ event, event ∈ initial.trace.events →
      OrdinaryValidatorEventCondition signature terminal event

/-- Empty inference history has open ordinary coverage. -/
theorem OpenOrdinaryValidatorEventCoverage.empty
    (signature : FrozenSig) (supply : InferenceBase.FreshSupply) :
    OpenOrdinaryValidatorEventCoverage signature (InferState.empty supply) := by
  intro terminal history producerSafe event membership
  simp [InferState.empty] at membership

/-- At the root terminal cut, open coverage yields exactly the three ordinary
coverage packages consumed by validator completeness. -/
theorem OpenOrdinaryValidatorEventCoverage.atTerminal
    {signature : FrozenSig} {state : InferState}
    (coverage : OpenOrdinaryValidatorEventCoverage signature state)
    (producerSafe : ProtectedProducerTrace state) :
    TraversalValidatorEventCoverage signature state ∧
      TraceTypeAlignmentConditions state ∧
      TraceDualAlignmentConditions state := by
  have terminal := coverage state (InferState.StateExtension.refl state)
    producerSafe
  refine ⟨?_, ?_, ?_⟩
  · intro event membership
    exact (terminal event membership).traversal
  · rw [traceTypeAlignmentConditions_iff_eventCoverage]
    intro event membership
    exact (terminal event membership).typeAlignment
  · rw [traceDualAlignmentConditions_iff_eventCoverage]
    intro event membership
    exact (terminal event membership).dualAlignment

/-- Extend an open prefix through an arbitrary successful append-only run.
Only genuinely new event values need local justification; an appended event
equal to an older event is already covered by the older witness. -/
theorem OpenOrdinaryValidatorEventCoverage.transportExtension
    {signature : FrozenSig} {earlier later : InferState}
    (before : OpenOrdinaryValidatorEventCoverage signature earlier)
    (history : earlier.StateExtension later)
    (newEvents : ∀ event,
      event ∈ later.trace.events → event ∉ earlier.trace.events →
      ∀ terminal, later.StateExtension terminal →
        ProtectedProducerTrace terminal →
        OrdinaryValidatorEventCondition signature terminal event) :
    OpenOrdinaryValidatorEventCoverage signature later := by
  intro terminal suffix producerSafe event membership
  by_cases previous : event ∈ earlier.trace.events
  · exact before terminal (history.trans suffix) producerSafe event previous
  · exact newEvents event membership previous terminal suffix producerSafe

/-- Solver/allocation updates that emit no event transport open coverage
without any additional semantic premise. -/
theorem OpenOrdinaryValidatorEventCoverage.transportNoEvents
    {signature : FrozenSig} {earlier later : InferState}
    (before : OpenOrdinaryValidatorEventCoverage signature earlier)
    (history : earlier.StateExtension later)
    (eventsEq : later.trace.events = earlier.trace.events) :
    OpenOrdinaryValidatorEventCoverage signature later := by
  apply before.transportExtension history
  intro event membership previous terminal suffix producerSafe
  exfalso
  apply previous
  simpa [eventsEq] using membership

/-- Append one locally justified event.  The local premise is deliberately
future-open, matching the emitter lemmas for type, dual, instance, and slot
events. -/
theorem OpenOrdinaryValidatorEventCoverage.recordEvent
    {signature : FrozenSig} {state : InferState} {event : TraceEvent}
    (before : OpenOrdinaryValidatorEventCoverage signature state)
    (latest : ∀ terminal,
      (state.recordEvent event).StateExtension terminal →
        ProtectedProducerTrace terminal →
        OrdinaryValidatorEventCondition signature terminal event) :
    OpenOrdinaryValidatorEventCoverage signature
      (state.recordEvent event) := by
  intro terminal suffix producerSafe candidate membership
  simp only [InferState.recordEvent, List.mem_append,
    List.mem_singleton] at membership
  rcases membership with previous | newest
  · exact before terminal
      ((state.stateExtension_recordEvent event).trans suffix)
      producerSafe candidate previous
  · subst candidate
    exact latest terminal suffix producerSafe

/-! ## Composable successful-traversal certificates -/

/-- The validator-relevant content of one successful executable traversal.
It records append-only history and justifies precisely the event values added
by the traversal, uniformly at every later safe terminal cut.  Each of the
mutually recursive executable families can return this certificate alongside
its ordinary result without mentioning the final root validator. -/
structure OrdinaryValidatorHistoryExtension
    (signature : FrozenSig) (earlier later : InferState) : Prop where
  history : earlier.StateExtension later
  newEvents : ∀ event,
    event ∈ later.trace.events → event ∉ earlier.trace.events →
    ∀ terminal, later.StateExtension terminal →
      ProtectedProducerTrace terminal →
      OrdinaryValidatorEventCondition signature terminal event

/-- A traversal which does not change state contributes no event. -/
theorem OrdinaryValidatorHistoryExtension.refl
    (signature : FrozenSig) (state : InferState) :
    OrdinaryValidatorHistoryExtension signature state state := by
  refine ⟨InferState.StateExtension.refl state, ?_⟩
  intro event membership previous
  exact False.elim (previous membership)

/-- Chronological successful traversals compose.  The set-difference form of
`newEvents` also handles duplicate event values: a duplicate already covered
by the first traversal needs no second witness. -/
theorem OrdinaryValidatorHistoryExtension.trans
    {signature : FrozenSig} {first middle last : InferState}
    (front : OrdinaryValidatorHistoryExtension signature first middle)
    (back : OrdinaryValidatorHistoryExtension signature middle last) :
    OrdinaryValidatorHistoryExtension signature first last := by
  refine ⟨front.history.trans back.history, ?_⟩
  intro event finalMembership notFirst terminal suffix producerSafe
  by_cases inMiddle : event ∈ middle.trace.events
  · exact front.newEvents event inMiddle notFirst terminal
      (back.history.trans suffix) producerSafe
  · exact back.newEvents event finalMembership inMiddle terminal suffix
      producerSafe

/-- A completed traversal certificate advances any open prefix invariant. -/
theorem OrdinaryValidatorHistoryExtension.applyCoverage
    {signature : FrozenSig} {earlier later : InferState}
    (extension : OrdinaryValidatorHistoryExtension signature earlier later)
    (before : OpenOrdinaryValidatorEventCoverage signature earlier) :
    OpenOrdinaryValidatorEventCoverage signature later :=
  before.transportExtension extension.history extension.newEvents

/-- Package an event-free history extension. -/
theorem OrdinaryValidatorHistoryExtension.ofNoEvents
    {signature : FrozenSig} {earlier later : InferState}
    (history : earlier.StateExtension later)
    (eventsEq : later.trace.events = earlier.trace.events) :
    OrdinaryValidatorHistoryExtension signature earlier later := by
  refine ⟨history, ?_⟩
  intro event membership previous
  exfalso
  apply previous
  simpa [eventsEq] using membership

/-- Package one explicit event append. -/
theorem OrdinaryValidatorHistoryExtension.recordEvent
    {signature : FrozenSig} {state : InferState} {event : TraceEvent}
    (latest : ∀ terminal,
      (state.recordEvent event).StateExtension terminal →
      ProtectedProducerTrace terminal →
      OrdinaryValidatorEventCondition signature terminal event) :
    OrdinaryValidatorHistoryExtension signature state
      (state.recordEvent event) := by
  refine ⟨state.stateExtension_recordEvent event, ?_⟩
  intro candidate membership previous terminal suffix producerSafe
  simp only [InferState.recordEvent, List.mem_append,
    List.mem_singleton] at membership
  rcases membership with old | newest
  · exact False.elim (previous old)
  · subst candidate
    exact latest terminal suffix producerSafe

/-- Append one validator-neutral event. -/
theorem OrdinaryValidatorHistoryExtension.recordNeutral
    {signature : FrozenSig} {state : InferState} {event : TraceEvent}
    (neutral : ValidatorNeutralEvent event) :
    OrdinaryValidatorHistoryExtension signature state
      (state.recordEvent event) :=
  OrdinaryValidatorHistoryExtension.recordEvent fun terminal _history _safe =>
    neutral.ordinaryCondition signature terminal

/-- Syntax-node visits are neutral event appends. -/
theorem OrdinaryValidatorHistoryExtension.visit
    (signature : FrozenSig) (state : InferState)
    (kind : NodeKind) (path : SyntaxPath) :
    OrdinaryValidatorHistoryExtension signature state
      (TypePM.Inference.visit state kind path) := by
  simpa [TypePM.Inference.visit] using
    (OrdinaryValidatorHistoryExtension.recordNeutral
      (signature := signature) (state := state)
      (ValidatorNeutralEvent.visit kind path))

/-- Final expression recording is a neutral event append. -/
theorem OrdinaryValidatorHistoryExtension.finishExpr
    (signature : FrozenSig) (state : InferState)
    (expression : Expr) (path : SyntaxPath) (target : Ty) :
    OrdinaryValidatorHistoryExtension signature state
      (TypePM.Inference.finishExpr expression path target state).state := by
  simpa [TypePM.Inference.finishExpr] using
    (OrdinaryValidatorHistoryExtension.recordNeutral
      (signature := signature) (state := state)
      (ValidatorNeutralEvent.inferredExpr expression target path))

/-- Recording provenance without an event does not affect ordinary coverage. -/
theorem OrdinaryValidatorHistoryExtension.recordSource
    (signature : FrozenSig) (state : InferState) (source : ProducerSource) :
    OrdinaryValidatorHistoryExtension signature state
      (state.recordSource source) :=
  OrdinaryValidatorHistoryExtension.ofNoEvents
    (state.stateExtension_recordSource source) (by rfl)

/-- Direct-self recording composes one neutral event with a source-only
update. -/
theorem OrdinaryValidatorHistoryExtension.recordSelfReference
    (signature : FrozenSig) (state : InferState)
    (binder : String) (placeholder : Ty) (path : SyntaxPath) :
    OrdinaryValidatorHistoryExtension signature state
      (TypePM.Inference.recordSelfReference state binder placeholder path) := by
  unfold TypePM.Inference.recordSelfReference
  exact (OrdinaryValidatorHistoryExtension.recordNeutral
    (signature := signature) (state := state)
    (ValidatorNeutralEvent.directSelfReference binder placeholder path)).trans
      (OrdinaryValidatorHistoryExtension.recordSource signature _ _)

/-- Protecting a finalized matcher changes no event history. -/
theorem OrdinaryValidatorHistoryExtension.protectMatcherCapability
    (signature : FrozenSig) (state : InferState) (capability : Cap) :
    OrdinaryValidatorHistoryExtension signature state
      (state.protectMatcherCapability capability) :=
  OrdinaryValidatorHistoryExtension.ofNoEvents
    (state.stateExtension_protectMatcherCapability capability) (by rfl)

/-- Selective matcher protection likewise changes no event history. -/
theorem OrdinaryValidatorHistoryExtension.protectMatcherCapabilityExcept
    (signature : FrozenSig) (state : InferState) (capability : Cap)
    (borrowed : List CapVar) :
    OrdinaryValidatorHistoryExtension signature state
      (state.protectMatcherCapabilityExcept capability borrowed) :=
  OrdinaryValidatorHistoryExtension.ofNoEvents
    (state.stateExtension_protectMatcherCapabilityExcept capability borrowed)
    (by rfl)

/-- Fresh target allocation appends only its neutral allocation event. -/
theorem OrdinaryValidatorHistoryExtension.freshTy
    (signature : FrozenSig) (state : InferState) (origin : ConstraintOrigin) :
    OrdinaryValidatorHistoryExtension signature state
      (state.freshTy origin).2 := by
  refine ⟨state.stateExtension_freshTy origin, ?_⟩
  intro event membership previous terminal suffix producerSafe
  simp only [InferState.freshTy, InferenceBase.freshTyMeta,
    InferState.recordEvent, List.mem_append, List.mem_singleton] at membership
  rcases membership with old | newest
  · exact False.elim (previous old)
  · subst event
    exact (ValidatorNeutralEvent.freshTy origin state.supply.nextTy
      ).ordinaryCondition signature terminal

/-- Fresh capability allocation appends only its neutral allocation event. -/
theorem OrdinaryValidatorHistoryExtension.freshCap
    (signature : FrozenSig) (state : InferState) (origin : ConstraintOrigin) :
    OrdinaryValidatorHistoryExtension signature state
      (state.freshCap origin).2 := by
  refine ⟨state.stateExtension_freshCap origin, ?_⟩
  intro event membership previous terminal suffix producerSafe
  simp only [InferState.freshCap, InferenceBase.freshCapMeta,
    InferState.recordEvent, List.mem_append, List.mem_singleton] at membership
  rcases membership with old | newest
  · exact False.elim (previous old)
  · subst event
    exact (ValidatorNeutralEvent.freshCap origin ⟨state.supply.nextCap⟩
      ).ordinaryCondition signature terminal

/-- Export freezing appends one neutral bookkeeping event. -/
theorem OrdinaryValidatorHistoryExtension.freezeCapabilityExport
    (signature : FrozenSig) (state : InferState)
    (capImages : List CapVar) (exportedPayload : Ty) :
    OrdinaryValidatorHistoryExtension signature state
      (state.freezeCapabilityExport capImages exportedPayload) := by
  refine ⟨state.stateExtension_freezeCapabilityExport capImages
    exportedPayload, ?_⟩
  intro event membership previous terminal suffix producerSafe
  simp only [InferState.freezeCapabilityExport, InferState.recordEvent,
    List.mem_append, List.mem_singleton] at membership
  rcases membership with old | newest
  · exact False.elim (previous old)
  · subst event
    exact (ValidatorNeutralEvent.capabilityExportFreeze
      state.trace.solves.length capImages exportedPayload
      (state.prevailing.apply exportedPayload)
      (capabilityExportLeaves state capImages exportedPayload)
      ).ordinaryCondition signature terminal

/-- Closed constructor instantiation is one canonical-instance event append. -/
theorem OrdinaryValidatorHistoryExtension.instantiateCtorInState
    {signature : FrozenSig} (state : InferState) (scheme : CtorScheme)
    (closed : scheme.Closed) :
    OrdinaryValidatorHistoryExtension signature state
      (TypePM.Inference.instantiateCtorInState state scheme).2 := by
  have stateExtension := instantiateCtorInState_stateExtension state scheme
  refine ⟨stateExtension, ?_⟩
  intro event membership previous terminal suffix producerSafe
  simp only [TypePM.Inference.instantiateCtorInState,
    InferState.recordEvent, List.mem_append,
    List.mem_singleton] at membership
  rcases membership with old | newest
  · exact False.elim (previous old)
  · subst event
    apply ctorInstantiation_ordinaryValidatorEventCondition closed
    exact (stateExtension.trans suffix).history.solve_length_le

/-- Context-scheme instantiation extension.  The only nonlocal input is the
terminal lookup equation, which is owned by context bisimulation rather than
by the state-history layer. -/
theorem OrdinaryValidatorHistoryExtension.instantiateSchemeInState
    {signature : FrozenSig} {rawContext normalizedContext : Context}
    {name : String} {state : InferState} {scheme : Scheme}
    (terminalLookup : ∀ terminal,
      (TypePM.Inference.instantiateSchemeInState signature rawContext
        normalizedContext name state scheme).2.StateExtension terminal →
      (rawContext.applySubst terminal.prevailing).find? name =
        some (scheme.applyMeta terminal.prevailing)) :
    OrdinaryValidatorHistoryExtension signature state
      (TypePM.Inference.instantiateSchemeInState signature rawContext
        normalizedContext name state scheme).2 := by
  let output := (TypePM.Inference.instantiateSchemeInState signature rawContext
    normalizedContext name state scheme).2
  have stateExtension := instantiateSchemeInState_stateExtension signature
    rawContext normalizedContext name state scheme
  refine ⟨stateExtension, ?_⟩
  intro event membership previous terminal suffix producerSafe
  simp only [TypePM.Inference.instantiateSchemeInState,
    InferState.recordEvent, List.mem_append,
    List.mem_singleton] at membership
  rcases membership with old | newest
  · exact False.elim (previous old)
  · subst event
    apply schemeInstantiation_ordinaryValidatorEventCondition
      ((stateExtension.trans suffix).history.solve_length_le)
      (terminalLookup terminal suffix) producerSafe
    intro image imageMembership
    apply suffix.protectedCaps
    simp only [TypePM.Inference.instantiateSchemeInState,
      InferState.recordEvent, List.mem_append]
    exact Or.inr imageMembership

/-- Closed dual-scheme instantiation extension. -/
theorem OrdinaryValidatorHistoryExtension.instantiateDualInState
    {signature : FrozenSig} {rawContext : Context}
    {rawParameters : PatternCtx} {rawBindings : MonoCtx} {context : Context}
    {parameters : PatternCtx} {bindings : MonoCtx} {state : InferState}
    {scheme : DualScheme} (closed : scheme.Closed) :
    OrdinaryValidatorHistoryExtension signature state
      (TypePM.Inference.instantiateDualInState signature rawContext
        rawParameters rawBindings context parameters bindings state scheme).2 := by
  let output := (TypePM.Inference.instantiateDualInState signature rawContext
    rawParameters rawBindings context parameters bindings state scheme).2
  have stateExtension := instantiateDualInState_stateExtension signature
    rawContext rawParameters rawBindings context parameters bindings state scheme
  refine ⟨stateExtension, ?_⟩
  intro event membership previous terminal suffix producerSafe
  simp only [TypePM.Inference.instantiateDualInState,
    InferState.recordEvent, List.mem_append,
    List.mem_singleton] at membership
  rcases membership with old | newest
  · exact False.elim (previous old)
  · subst event
    apply dualInstantiation_ordinaryValidatorEventCondition closed
      ((stateExtension.trans suffix).history.solve_length_le) producerSafe
    intro image imageMembership
    apply suffix.protectedCaps
    simp only [TypePM.Inference.instantiateDualInState,
      InferState.recordEvent, List.mem_append]
    exact Or.inr imageMembership

/-! ## Alignment-event finishers -/

/-- Append the public type-alignment event after an already covered core
alignment run. -/
theorem OrdinaryValidatorHistoryExtension.finishAlignTypes
    {signature : FrozenSig} {state aligned : InferState}
    {origin : ConstraintOrigin} {left right : Ty}
    (core : OrdinaryValidatorHistoryExtension signature state aligned)
    (success : alignTypes state origin left right = some
      (aligned.recordEvent (.typeAlignment state.trace.solves.length
        aligned.trace.solves.length left right (state.prevailing.apply left)
        (state.prevailing.apply right)))) :
    OrdinaryValidatorHistoryExtension signature state
      (aligned.recordEvent (.typeAlignment state.trace.solves.length
        aligned.trace.solves.length left right (state.prevailing.apply left)
        (state.prevailing.apply right))) := by
  let event := TraceEvent.typeAlignment state.trace.solves.length
    aligned.trace.solves.length left right (state.prevailing.apply left)
    (state.prevailing.apply right)
  apply core.trans
  apply OrdinaryValidatorHistoryExtension.recordEvent
  intro terminal suffix producerSafe
  have condition := alignTypes_ordinaryValidatorEventCondition
    (signature := signature) success suffix.history
  simpa [event, InferState.recordEvent] using condition

/-- Append the public dual-alignment event after its already covered internal
capability/type run. -/
theorem OrdinaryValidatorHistoryExtension.finishAlignDuals
    {signature : FrozenSig} {state aligned : InferState}
    {origin : ConstraintOrigin} {left right : Dual}
    (core : OrdinaryValidatorHistoryExtension signature state aligned)
    (success : alignDuals state origin left right = some
      (aligned.recordEvent (.dualAlignment state.trace.solves.length
        aligned.trace.solves.length left right
        (left.applySubst state.prevailing)
        (right.applySubst state.prevailing)))) :
    OrdinaryValidatorHistoryExtension signature state
      (aligned.recordEvent (.dualAlignment state.trace.solves.length
        aligned.trace.solves.length left right
        (left.applySubst state.prevailing)
        (right.applySubst state.prevailing))) := by
  let event := TraceEvent.dualAlignment state.trace.solves.length
    aligned.trace.solves.length left right (left.applySubst state.prevailing)
    (right.applySubst state.prevailing)
  apply core.trans
  apply OrdinaryValidatorHistoryExtension.recordEvent
  intro terminal suffix producerSafe
  have condition := alignDuals_ordinaryValidatorEventCondition
    (signature := signature) success suffix.history
  simpa [event, InferState.recordEvent] using condition

/-- Append the expected-slot event after the selected underlying alignment
has already been covered. -/
theorem OrdinaryValidatorHistoryExtension.finishExpectedAlignment
    {signature : FrozenSig} {path : SyntaxPath}
    {expressionResult : ExprResult} {expected : Ty} {aligned : InferState}
    (core : OrdinaryValidatorHistoryExtension signature
      expressionResult.state aligned)
    (success : alignExprResultAtExpected path expressionResult expected = some
      (aligned.recordEvent (.slotAlignment
        expressionResult.state.trace.solves.length
        aligned.trace.solves.length
        (match expectedCoercionPlan expressionResult.state
            expressionResult.target expected with
          | .productMatcherLift duals => productMatcherTarget duals
          | .slotTupleLift duals => slotTupleTarget duals
          | .raw => expressionResult.state.prevailing.apply
              expressionResult.target)
        (expressionResult.state.prevailing.apply expected)))) :
    OrdinaryValidatorHistoryExtension signature expressionResult.state
      (aligned.recordEvent (.slotAlignment
        expressionResult.state.trace.solves.length
        aligned.trace.solves.length
        (match expectedCoercionPlan expressionResult.state
            expressionResult.target expected with
          | .productMatcherLift duals => productMatcherTarget duals
          | .slotTupleLift duals => slotTupleTarget duals
          | .raw => expressionResult.state.prevailing.apply
              expressionResult.target)
        (expressionResult.state.prevailing.apply expected))) := by
  let inferred := match expectedCoercionPlan expressionResult.state
      expressionResult.target expected with
    | .productMatcherLift duals => productMatcherTarget duals
    | .slotTupleLift duals => slotTupleTarget duals
    | .raw => expressionResult.state.prevailing.apply expressionResult.target
  let requested := expressionResult.state.prevailing.apply expected
  let event := TraceEvent.slotAlignment
    expressionResult.state.trace.solves.length aligned.trace.solves.length
    inferred requested
  apply core.trans
  apply OrdinaryValidatorHistoryExtension.recordEvent
  intro terminal suffix producerSafe
  have condition :=
    alignExprResultAtExpected_ordinaryValidatorEventCondition
      (signature := signature) success suffix.history
  simpa [event, inferred, requested, InferState.recordEvent] using condition

/-- Bundle the two independent recursion products needed at the final root:
ordinary coverage from executable traversal and sensitive coverage from the
terminal-audited origin recursion. -/
structure RootValidatorEventCoverage
    (terminal : Subst) (signature : FrozenSig) (state : InferState) : Prop where
  ordinary : OpenOrdinaryValidatorEventCoverage signature state
  sensitive : TerminalAuditEventCoverage terminal signature state

/-- The combined root certificate projects to the four premises used by the
existing validator assembly theorem. -/
theorem RootValidatorEventCoverage.atTerminal
    {terminal : Subst} {signature : FrozenSig} {state : InferState}
    (coverage : RootValidatorEventCoverage terminal signature state)
    (producerSafe : ProtectedProducerTrace state) :
    TraversalValidatorEventCoverage signature state ∧
      TerminalAuditEventCoverage terminal signature state ∧
      TraceTypeAlignmentConditions state ∧
      TraceDualAlignmentConditions state := by
  obtain ⟨traversal, types, duals⟩ :=
    coverage.ordinary.atTerminal producerSafe
  exact ⟨traversal, coverage.sensitive, types, duals⟩

/-! ## Composable sensitive-audit extensions -/

/-- The pointwise clause used by `TerminalAuditEventCoverage`. -/
def TerminalAuditCoveredEvent
    (terminal : Subst) (signature : FrozenSig) (state : InferState)
    (event : TraceEvent) : Prop :=
  match event with
  | .patternCtorCompatibility _ _ _ _
  | .matcherFinalization _ _ _ _ _ _ _ _
  | .letGeneralization _ _ _ _ _ _ _ =>
      TerminalAuditEventWitness terminal signature state event
  | _ => True

/-- A sensitive-event clause transports through a later executable state
extension. -/
theorem TerminalAuditCoveredEvent.transport
    {terminal : Subst} {signature : FrozenSig} {earlier later : InferState}
    {event : TraceEvent}
    (covered : TerminalAuditCoveredEvent terminal signature earlier event)
    (extension : earlier.StateExtension later) :
    TerminalAuditCoveredEvent terminal signature later event := by
  cases event <;> try trivial
  all_goals exact TerminalAuditEventWitness.transport covered extension.history

/-- Incremental counterpart of `TerminalAuditEventCoverage`.  It records only
the sensitive event values introduced between two traversal cuts. -/
structure TerminalAuditHistoryExtension
    (terminal : Subst) (signature : FrozenSig)
    (earlier later : InferState) : Prop where
  state : earlier.StateExtension later
  newEvents : ∀ event,
    event ∈ later.trace.events → event ∉ earlier.trace.events →
      TerminalAuditCoveredEvent terminal signature later event

theorem TerminalAuditHistoryExtension.refl
    (terminal : Subst) (signature : FrozenSig) (state : InferState) :
    TerminalAuditHistoryExtension terminal signature state state := by
  refine ⟨InferState.StateExtension.refl state, ?_⟩
  intro event membership previous
  exact False.elim (previous membership)

theorem TerminalAuditHistoryExtension.trans
    {terminal : Subst} {signature : FrozenSig}
    {first middle last : InferState}
    (front : TerminalAuditHistoryExtension terminal signature first middle)
    (back : TerminalAuditHistoryExtension terminal signature middle last) :
    TerminalAuditHistoryExtension terminal signature first last := by
  refine ⟨front.state.trans back.state, ?_⟩
  intro event finalMembership notFirst
  by_cases inMiddle : event ∈ middle.trace.events
  · exact (front.newEvents event inMiddle notFirst).transport back.state
  · exact back.newEvents event finalMembership inMiddle

/-- Advance absolute sensitive coverage through an incremental extension. -/
theorem TerminalAuditHistoryExtension.applyCoverage
    {terminal : Subst} {signature : FrozenSig}
    {earlier later : InferState}
    (extension : TerminalAuditHistoryExtension terminal signature earlier later)
    (before : TerminalAuditEventCoverage terminal signature earlier) :
    TerminalAuditEventCoverage terminal signature later := by
  intro event membership
  by_cases previous : event ∈ earlier.trace.events
  · have covered := before event previous
    cases event <;> try trivial
    all_goals exact TerminalAuditEventWitness.transport covered extension.state.history
  · exact extension.newEvents event membership previous

/-- Any state extension which emits no sensitive event is an audit extension. -/
theorem TerminalAuditHistoryExtension.ofOrdinary
    {terminal : Subst} {signature : FrozenSig}
    {earlier later : InferState}
    (state : earlier.StateExtension later)
    (ordinaryNew : ∀ event,
      event ∈ later.trace.events → event ∉ earlier.trace.events →
        ¬ TerminalAuditSensitiveEvent event) :
    TerminalAuditHistoryExtension terminal signature earlier later := by
  refine ⟨state, ?_⟩
  intro event membership previous
  have ordinary := ordinaryNew event membership previous
  cases event <;> simp_all [TerminalAuditCoveredEvent,
    TerminalAuditSensitiveEvent]

/-- Append one already witnessed sensitive event. -/
theorem TerminalAuditHistoryExtension.recordSensitive
    {terminal : Subst} {signature : FrozenSig}
    {state : InferState} {event : TraceEvent}
    (witness : TerminalAuditEventWitness terminal signature
      (state.recordEvent event) event) :
    TerminalAuditHistoryExtension terminal signature state
      (state.recordEvent event) := by
  refine ⟨state.stateExtension_recordEvent event, ?_⟩
  intro candidate membership previous
  simp only [InferState.recordEvent, List.mem_append,
    List.mem_singleton] at membership
  rcases membership with old | newest
  · exact False.elim (previous old)
  · subst candidate
    cases event <;> try trivial
    all_goals exact witness

/-- Ordinary validator extensions can be reused on the sensitive side when
their newly appended events avoid the three audit forms. -/
theorem OrdinaryValidatorHistoryExtension.auditExtension
    {terminal : Subst} {signature : FrozenSig}
    {earlier later : InferState}
    (extension : OrdinaryValidatorHistoryExtension signature earlier later)
    (ordinaryNew : ∀ event,
      event ∈ later.trace.events → event ∉ earlier.trace.events →
        ¬ TerminalAuditSensitiveEvent event) :
    TerminalAuditHistoryExtension terminal signature earlier later :=
  TerminalAuditHistoryExtension.ofOrdinary extension.history ordinaryNew

end Reconstruction
end Inference
end TypePM
