import TypePM.P2.Runtime

/-!
# P2 non-CAS core source bridge

`RuntimeSpec` is a deliberately general proof kernel: it can be instantiated
by any functional relation between a runtime clause list and ShapeCap
evidence.  The formal core must expose a narrower boundary.  `CoreSpecWF`
therefore requires a deterministic evidence checker for each *actual*
`TypePM.Clause` under a static source context, folds that checker over the
runtime clause list in order, and keeps target typing and coverage as separate
obligations.

The checker receives no direct target-type or runtime-environment argument and
may inspect static typing information (in particular, the typed capability of
each pattern-pattern hole).  Because `SourceCtx` is abstract, the interface's
type alone does not prove that a concrete context representation contains no
target-derived seed; that is an explicit source-instantiation obligation.
`evidenceCoherent` says that two static contexts describing the same captured
runtime environment cannot assign different evidence to the same clause.
`substAdmissible` records when a coupled substitution can re-realize that
captured environment, rather than assuming that every target specialization
preserves its typing.  `literalSubstitute` is required only for the evidence
and intrinsic capability of the actual literal, under an admissible
substitution that fixes that intrinsic capability.  A concrete source calculus
must instantiate these fields with the clause-evidence rules specified in the
current TeX draft and with two-sorted substitution lemmas.  Those
source-calculus discharges remain obligations; this interface does not turn
them into proved open-term source theorems.

CAS views, raw-signature validation, general producer-flow reconstruction,
and Egison's ordinary warning mode are outside this interface.
-/

namespace TypePM.P2

/--
Fold a deterministic, context-indexed per-clause checker over an actual clause
list while preserving order.
-/
def collectClauseEvidence
    {StaticCtx : Type}
    (checker : StaticCtx → Clause → Option Shape.Evidence)
    (Γ : StaticCtx) :
    List Clause → Option (List Shape.Evidence)
  | [] => some []
  | clause :: clauses =>
      (checker Γ clause).bind fun evidence =>
        (collectClauseEvidence checker Γ clauses).map (evidence :: ·)

/-- A successful checker fold has exactly one result per source clause. -/
theorem collectClauseEvidence_length
    {StaticCtx : Type}
    (checker : StaticCtx → Clause → Option Shape.Evidence)
    {Γ : StaticCtx}
    {clauses : List Clause}
    {evidence : List Shape.Evidence}
    (hcollect :
      collectClauseEvidence checker Γ clauses = some evidence) :
    evidence.length = clauses.length := by
  induction clauses generalizing evidence with
  | nil =>
      simp [collectClauseEvidence] at hcollect
      subst evidence
      rfl
  | cons clause clauses ih =>
      simp only [collectClauseEvidence] at hcollect
      cases hhead : checker Γ clause with
      | none =>
          simp [hhead] at hcollect
      | some headEvidence =>
          cases htail : collectClauseEvidence checker Γ clauses with
          | none =>
              simp [hhead, htail] at hcollect
          | some tailEvidence =>
              simp [hhead, htail] at hcollect
              subst evidence
              simp [ih htail]

/--
Well-formed source interface for the non-CAS formal core.

Evidence is generated by a deterministic checker on each actual source
clause under a static source context.  The checker may use typed hole
capabilities that are absent from the type-erased runtime `Clause`.  A
concrete instantiation must additionally show that its static context and
checker do not manufacture evidence from the literal target or runtime values.
`sourceEnvTyped`, `literalTyped`, and `coverageOK` stand for source-calculus
judgments whose concrete Lean definitions remain to be supplied; this
interface records precisely the coherence, substitution, and runtime
obligations needed by the algebraic P2 layer.
-/
structure CoreSpecWF where
  observability : Shape.Observability
  SourceCtx : Type
  sourceEnvTyped : SourceCtx → Env → Prop
  literalTyped : SourceCtx → List Clause → Ty → Prop
  clauseEvidence : SourceCtx → Clause → Option Shape.Evidence
  substAdmissible : SourceCtx → CapSubst → TySubst → Prop
  evidenceCoherent :
    ∀ {Γ₁ Γ₂ ρ clause},
      sourceEnvTyped Γ₁ ρ →
      sourceEnvTyped Γ₂ ρ →
      clauseEvidence Γ₁ clause = clauseEvidence Γ₂ clause
  literalSubstitute :
    ∀ {Γ ρ cls evidence cap target},
      sourceEnvTyped Γ ρ →
      literalTyped Γ cls target →
      collectClauseEvidence clauseEvidence Γ cls = some evidence →
      Shape.inferShape observability evidence = some cap →
      ∀ (C : CapSubst) (T : TySubst),
        cap.apply C = cap →
        substAdmissible Γ C T →
        ∃ Γ',
          sourceEnvTyped Γ' ρ ∧
            literalTyped Γ' cls (applyBoth C T target)
  coverageOK : List Clause → Cap → Prop

namespace CoreSpecWF

/--
Run the source clause-evidence checker on the actual runtime clause list.

The result has exactly one evidence tree per clause and preserves clause
order.  D1's `Shape.mergeAll` is subsequently permutation invariant, but the
bridge itself never invents, drops, or duplicates a clause.
-/
def collectEvidence
    (spec : CoreSpecWF) (Γ : spec.SourceCtx) :
    List Clause → Option (List Shape.Evidence) :=
  collectClauseEvidence spec.clauseEvidence Γ

@[simp] theorem collectEvidence_nil
    (spec : CoreSpecWF) (Γ : spec.SourceCtx) :
    spec.collectEvidence Γ [] = some [] :=
  rfl

/--
Static contexts that describe the same captured runtime environment compute
the same evidence for the same actual clause list.
-/
theorem collectEvidence_coherent
    (spec : CoreSpecWF)
    {Γ₁ Γ₂ : spec.SourceCtx} {ρ : Env}
    (henv₁ : spec.sourceEnvTyped Γ₁ ρ)
    (henv₂ : spec.sourceEnvTyped Γ₂ ρ)
    (clauses : List Clause) :
    spec.collectEvidence Γ₁ clauses =
      spec.collectEvidence Γ₂ clauses := by
  induction clauses with
  | nil => rfl
  | cons clause clauses ih =>
      unfold collectEvidence at ih
      simp only [collectEvidence, collectClauseEvidence]
      rw [spec.evidenceCoherent henv₁ henv₂, ih]

/--
A successful source bridge has exactly one evidence item per actual clause.
-/
theorem collectEvidence_length
    (spec : CoreSpecWF)
    {Γ : spec.SourceCtx}
    {clauses : List Clause}
    {evidence : List Shape.Evidence}
    (hcollect :
      spec.collectEvidence Γ clauses = some evidence) :
    evidence.length = clauses.length := by
  exact collectClauseEvidence_length spec.clauseEvidence hcollect

/--
Embed the well-formed source interface into the reusable runtime proof
kernel.  Evidence functionality is now derived from the deterministic
per-clause checker rather than supplied as an independent assumption.
-/
def toRuntimeSpec (spec : CoreSpecWF) : RuntimeSpec where
  observability := spec.observability
  literalTyped := fun ρ clauses target =>
    ∃ Γ, spec.sourceEnvTyped Γ ρ ∧
      spec.literalTyped Γ clauses target
  clauseEvidence := fun ρ clauses evidence =>
    ∃ Γ, spec.sourceEnvTyped Γ ρ ∧
      spec.collectEvidence Γ clauses = some evidence
  substAdmissible := fun ρ C T =>
    ∀ Γ, spec.sourceEnvTyped Γ ρ →
      spec.substAdmissible Γ C T
  evidenceUnique := by
    intro ρ clauses left right hleft hright
    rcases hleft with ⟨Γ₁, henv₁, hcollect₁⟩
    rcases hright with ⟨Γ₂, henv₂, hcollect₂⟩
    exact Option.some.inj
      (hcollect₁.symm.trans
        ((spec.collectEvidence_coherent henv₁ henv₂ clauses).trans
          hcollect₂))
  literalSubstitute := by
    intro ρ clauses evidence cap target
      hliteral hsource hshape C T hcap hadmissible
    rcases hliteral with ⟨Γ, henv, htyped⟩
    rcases hsource with ⟨Γe, henve, hcollecte⟩
    have hcollect :
        spec.collectEvidence Γ clauses = some evidence := by
      rw [spec.collectEvidence_coherent henv henve clauses]
      exact hcollecte
    rcases spec.literalSubstitute
        henv htyped hcollect hshape C T hcap
          (hadmissible Γ henv) with
      ⟨Γ', henv', htyped'⟩
    exact ⟨Γ', henv', htyped'⟩
  coverageOK := spec.coverageOK

/--
Build a runtime matcher certificate only from the well-formed source bridge.

The inferred capability comes from the evidence of the actual clauses.
Target typing, `CapTargetOK`, and coverage remain separate premises and cannot
act as ShapeCap seeds.  This public source boundary constructs only a covered
certificate; `MatcherCert.toOrdinary` is the one-way proof-internal erasure.
-/
def certify
    (spec : CoreSpecWF)
    {Ξ : List (Cap × Ty)}
    {Γ : spec.SourceCtx}
    {ρ : Env} {clauses : List Clause}
    {cap : Cap} {target : Ty}
    {evidence : List Shape.Evidence}
    (henv : spec.sourceEnvTyped Γ ρ)
    (hliteral : spec.literalTyped Γ clauses target)
    (hevidence :
      spec.collectEvidence Γ clauses = some evidence)
    (hshape :
      Shape.inferShape spec.observability evidence = some cap)
    (htarget : CapTargetOK Ξ cap target)
    (hcoverage : spec.coverageOK clauses cap) :
    MatcherCert spec.toRuntimeSpec .covered Ξ
      ρ clauses cap target where
  evidence := evidence
  literalTyped := ⟨Γ, henv, hliteral⟩
  sourceEvidence := ⟨Γ, henv, hevidence⟩
  shape := hshape
  targetOK := htarget
  coverage := hcoverage

/--
The source certificate immediately types the corresponding runtime matcher
closure with its intrinsic two indices.  As with `certify`, the result is
covered rather than an additional ordinary source-acceptance path.
-/
def literalValueTy
    (spec : CoreSpecWF)
    {Ξ : List (Cap × Ty)}
    {Γ : spec.SourceCtx}
    {ρ : Env} {clauses : List Clause}
    {cap : Cap} {target : Ty}
    {evidence : List Shape.Evidence}
    (henv : spec.sourceEnvTyped Γ ρ)
    (hliteral : spec.literalTyped Γ clauses target)
    (hevidence :
      spec.collectEvidence Γ clauses = some evidence)
    (hshape :
      Shape.inferShape spec.observability evidence = some cap)
    (htarget : CapTargetOK Ξ cap target)
    (hcoverage : spec.coverageOK clauses cap) :
    MatcherValueTy spec.toRuntimeSpec .covered Ξ
      (.matcherV ρ clauses) cap target :=
  MatcherValueTy.literal
    (spec.certify henv hliteral hevidence hshape htarget hcoverage)

/--
The covered source bridge yields all three runtime invariants needed by the
non-CAS core: intrinsic matcher typing, one evidence item per actual clause,
and coverage of the inferred capability.
-/
theorem coveredLiteralInvariant
    (spec : CoreSpecWF)
    {Ξ : List (Cap × Ty)}
    {Γ : spec.SourceCtx}
    {ρ : Env} {clauses : List Clause}
    {cap : Cap} {target : Ty}
    {evidence : List Shape.Evidence}
    (henv : spec.sourceEnvTyped Γ ρ)
    (hliteral : spec.literalTyped Γ clauses target)
    (hevidence :
      spec.collectEvidence Γ clauses = some evidence)
    (hshape :
      Shape.inferShape spec.observability evidence = some cap)
    (htarget : CapTargetOK Ξ cap target)
    (hcoverage : spec.coverageOK clauses cap) :
    MatcherValueTy spec.toRuntimeSpec .covered Ξ
        (.matcherV ρ clauses) cap target ∧
      evidence.length = clauses.length ∧
      spec.coverageOK clauses cap := by
  exact ⟨
    spec.literalValueTy
      henv hliteral hevidence hshape htarget hcoverage,
    spec.collectEvidence_length hevidence,
    hcoverage⟩

/--
For a Ξ-closed source certificate, an admissible target
specialization preserves the same intrinsic capability.  Ξ-closed does not
mean that the captured runtime environment is closed; `hadmissible` is the
separate premise that permits that environment to be re-realized.  Clause
evidence is not rerun against the target and cannot be strengthened by the
target substitution.
-/
theorem closedLiteralTargetNonStrengthening
    (spec : CoreSpecWF)
    {Γ : spec.SourceCtx}
    {ρ : Env} {clauses : List Clause}
    {cap : Cap} {target : Ty}
    {evidence : List Shape.Evidence}
    (henv : spec.sourceEnvTyped Γ ρ)
    (hliteral : spec.literalTyped Γ clauses target)
    (hevidence :
      spec.collectEvidence Γ clauses = some evidence)
    (hshape :
      Shape.inferShape spec.observability evidence = some cap)
    (htarget : CapTargetOK [] cap target)
    (hcoverage : spec.coverageOK clauses cap)
    (T : TySubst)
    (hadmissible :
      spec.toRuntimeSpec.substAdmissible ρ CapSubst.id T) :
    MatcherValueTy spec.toRuntimeSpec .covered []
      (.matcherV ρ clauses) cap (target.applyTarget T) :=
  (spec.literalValueTy
    henv hliteral hevidence hshape htarget hcoverage).targetSpecializeClosed
      T hadmissible

end CoreSpecWF
end TypePM.P2
