import TypePM.P2.Syntax

/-!
# D1 parameter observability

Parameter observability is a declaration-level property.  A direct occurrence
of a result parameter contributes a seed.  A recursive occurrence contributes
only a dependency edge: if the dependency is observable, the parameter that
uses it is observable as well.

This file computes the least solution of that finite Boolean dependency graph.
Rather than relying on an unverified convergence test, it enumerates the
`2 ^ nodeCount` Boolean valuations structurally and intersects all valuations
that contain the seeds and are closed under reverse dependency.  This is a
finite construction of the same least fixpoint and makes minimality explicit.
-/

namespace TypePM.P2
namespace Observability

/-- A Boolean observability valuation for a graph with `nodeCount` nodes. -/
abbrev Valuation (nodeCount : Nat) := Fin nodeCount → Bool

/--
A dependency `(user, dependency)` means that observability of `dependency`
propagates backwards to `user`.
-/
structure Graph where
  nodeCount : Nat
  seeds : List (Fin nodeCount)
  dependencies : List (Fin nodeCount × Fin nodeCount)
deriving Repr

/-- Add a Boolean head to a valuation of one fewer node. -/
def prepend {n : Nat} (head : Bool) (tail : Valuation n) :
    Valuation (n + 1) :=
  Fin.cases head tail

/-- All Boolean valuations, generated by structural recursion on node count. -/
def valuations : (n : Nat) → List (Valuation n)
  | 0 => [fun node => Fin.elim0 node]
  | n + 1 =>
      (valuations n).map (prepend false) ++
        (valuations n).map (prepend true)

/-- Every Boolean valuation occurs in the finite enumeration. -/
theorem mem_valuations {n : Nat} (valuation : Valuation n) :
    valuation ∈ valuations n := by
  induction n with
  | zero =>
      have valuation_eq : valuation = fun node => Fin.elim0 node := by
        funext node
        exact Fin.elim0 node
      simp [valuations, valuation_eq]
  | succ n ih =>
      let tail : Valuation n := fun node => valuation node.succ
      have tail_mem : tail ∈ valuations n := ih tail
      cases head_eq : valuation ⟨0, Nat.zero_lt_succ n⟩ with
      | false =>
          have valuation_eq : valuation = prepend false tail := by
            funext node
            refine Fin.cases ?_ (fun predecessor => ?_) node
            · simpa [prepend] using head_eq
            · rfl
          rw [valuation_eq]
          simp only [valuations, List.mem_append, List.mem_map]
          exact Or.inl ⟨tail, tail_mem, rfl⟩
      | true =>
          have valuation_eq : valuation = prepend true tail := by
            funext node
            refine Fin.cases ?_ (fun predecessor => ?_) node
            · simpa [prepend] using head_eq
            · rfl
          rw [valuation_eq]
          simp only [valuations, List.mem_append, List.mem_map]
          exact Or.inr ⟨tail, tail_mem, rfl⟩

/--
A closed valuation contains every seed and propagates truth from a dependency
to each of its users.
-/
def Closed (graph : Graph) (valuation : Valuation graph.nodeCount) : Prop :=
  (∀ node ∈ graph.seeds, valuation node = true) ∧
    (∀ edge ∈ graph.dependencies,
      valuation edge.2 = true → valuation edge.1 = true)

/-- Executable recognition of closed valuations. -/
def closedb (graph : Graph) (valuation : Valuation graph.nodeCount) : Bool :=
  graph.seeds.all (fun node => valuation node) &&
    graph.dependencies.all
      (fun edge => !valuation edge.2 || valuation edge.1)

theorem closedb_eq_true_iff
    {graph : Graph} {valuation : Valuation graph.nodeCount} :
    closedb graph valuation = true ↔ Closed graph valuation := by
  simp only [closedb, Bool.and_eq_true]
  constructor
  · rintro ⟨seeds_true, dependencies_true⟩
    constructor
    · intro node node_mem
      exact List.all_eq_true.mp seeds_true node node_mem
    · intro edge edge_mem dependency_true
      have edge_closed :=
        List.all_eq_true.mp dependencies_true edge edge_mem
      simpa [dependency_true] using edge_closed
  · rintro ⟨seeds_closed, dependencies_closed⟩
    constructor
    · apply List.all_eq_true.mpr
      intro node node_mem
      exact seeds_closed node node_mem
    · apply List.all_eq_true.mpr
      intro edge edge_mem
      cases dependency_eq : valuation edge.2 with
      | false => rfl
      | true =>
          simpa using
            dependencies_closed edge edge_mem dependency_eq

/--
The least observability valuation.

An invalid candidate contributes `true` to the intersection and is therefore
ignored.  A valid candidate contributes its actual bit.
-/
def solve (graph : Graph) : Valuation graph.nodeCount :=
  fun node =>
    (valuations graph.nodeCount).all fun candidate =>
      !closedb graph candidate || candidate node

theorem solve_eq_true_iff (graph : Graph) (node : Fin graph.nodeCount) :
    solve graph node = true ↔
      ∀ candidate ∈ valuations graph.nodeCount,
        closedb graph candidate = true → candidate node = true := by
  constructor
  · intro solved candidate candidate_mem candidate_closed
    have candidate_clause :=
      List.all_eq_true.mp solved candidate candidate_mem
    simpa [candidate_closed] using candidate_clause
  · intro all_candidates
    apply List.all_eq_true.mpr
    intro candidate candidate_mem
    cases closed_eq : closedb graph candidate with
    | false => simp
    | true =>
        simp [all_candidates candidate candidate_mem closed_eq]

/-- The computed solution is below every closed valuation. -/
theorem solve_least
    {graph : Graph} {candidate : Valuation graph.nodeCount}
    (candidate_closed : Closed graph candidate)
    {node : Fin graph.nodeCount}
    (node_observable : solve graph node = true) :
    candidate node = true := by
  exact (solve_eq_true_iff graph node).mp node_observable candidate
    (mem_valuations candidate)
    (closedb_eq_true_iff.mpr candidate_closed)

/-- Every explicit seed is observable in the computed solution. -/
theorem solve_seed
    {graph : Graph} {node : Fin graph.nodeCount}
    (node_seeded : node ∈ graph.seeds) :
    solve graph node = true := by
  apply (solve_eq_true_iff graph node).mpr
  intro candidate _ candidate_closedb
  exact (closedb_eq_true_iff.mp candidate_closedb).1 node node_seeded

/-- Truth propagates from a dependency to its user in the solution. -/
theorem solve_dependency
    {graph : Graph} {user dependency : Fin graph.nodeCount}
    (edge_mem : (user, dependency) ∈ graph.dependencies)
    (dependency_observable : solve graph dependency = true) :
    solve graph user = true := by
  apply (solve_eq_true_iff graph user).mpr
  intro candidate _ candidate_closedb
  have candidate_closed := closedb_eq_true_iff.mp candidate_closedb
  exact candidate_closed.2 (user, dependency) edge_mem
    (solve_least candidate_closed dependency_observable)

/-- The finite intersection is itself seed-containing and dependency-closed. -/
theorem solve_closed (graph : Graph) : Closed graph (solve graph) := by
  constructor
  · intro node node_mem
    exact solve_seed node_mem
  · intro edge edge_mem dependency_observable
    exact solve_dependency edge_mem dependency_observable

/-- Reverse-dependency reachability from an explicit seed. -/
inductive Reachable (graph : Graph) : Fin graph.nodeCount → Prop where
  | seed {node} :
      node ∈ graph.seeds →
      Reachable graph node
  | reverseDependency {user dependency} :
      (user, dependency) ∈ graph.dependencies →
      Reachable graph dependency →
      Reachable graph user

/-- Boolean characteristic function of reverse-dependency reachability. -/
noncomputable def reachableValuation (graph : Graph) :
    Valuation graph.nodeCount :=
  fun node =>
    @decide (Reachable graph node) (Classical.propDecidable _)

/-- A seed and its entire reverse-dependency closure are observable. -/
theorem reachable_solve_true
    {graph : Graph} {node : Fin graph.nodeCount}
    (reachable : Reachable graph node) :
    solve graph node = true := by
  induction reachable with
  | seed node_seeded => exact solve_seed node_seeded
  | reverseDependency edge_mem _ dependency_ih =>
      exact solve_dependency edge_mem dependency_ih

/-- The characteristic valuation of graph reachability is closed. -/
theorem reachableValuation_closed (graph : Graph) :
    Closed graph (reachableValuation graph) := by
  classical
  constructor
  · intro node node_seeded
    exact decide_eq_true (Reachable.seed node_seeded)
  · intro edge edge_mem dependency_reachable
    exact decide_eq_true
      (Reachable.reverseDependency edge_mem
        (of_decide_eq_true dependency_reachable))

/-- The solver never marks a node that is unreachable from every seed. -/
theorem solve_sound
    {graph : Graph} {node : Fin graph.nodeCount}
    (node_observable : solve graph node = true) :
    Reachable graph node := by
  classical
  have reachable_bit :=
    solve_least (reachableValuation_closed graph) node_observable
  exact of_decide_eq_true reachable_bit

/-- Solver truth is exactly reverse-dependency reachability from a seed. -/
theorem solve_eq_true_iff_reachable
    {graph : Graph} {node : Fin graph.nodeCount} :
    solve graph node = true ↔ Reachable graph node :=
  ⟨solve_sound, reachable_solve_true⟩

/--
A node is false exactly when no seed reaches it through reverse dependencies.
This is the general recursive-only/no-seed result, including isolated cycles.
-/
theorem solve_eq_false_iff_not_reachable
    {graph : Graph} {node : Fin graph.nodeCount} :
    solve graph node = false ↔ ¬Reachable graph node := by
  constructor
  · intro node_false reachable
    have node_true := reachable_solve_true reachable
    simp [node_false] at node_true
  · intro not_reachable
    cases node_eq : solve graph node with
    | false => rfl
    | true => exact (not_reachable (solve_sound node_eq)).elim

/-- Pointwise inclusion between Boolean valuations. -/
def PointwiseLE {n : Nat} (left right : Valuation n) : Prop :=
  ∀ node, left node = true → right node = true

/-- The solver is pointwise below every closed valuation. -/
theorem solve_pointwise_least
    {graph : Graph} {candidate : Valuation graph.nodeCount}
    (candidate_closed : Closed graph candidate) :
    PointwiseLE (solve graph) candidate := by
  intro node node_observable
  exact solve_least candidate_closed node_observable

/-- Being a least closed valuation determines a solver result uniquely. -/
theorem least_closed_unique
    {graph : Graph} {left right : Valuation graph.nodeCount}
    (left_closed : Closed graph left)
    (right_closed : Closed graph right)
    (left_least :
      ∀ candidate, Closed graph candidate → PointwiseLE left candidate)
    (right_least :
      ∀ candidate, Closed graph candidate → PointwiseLE right candidate) :
    left = right := by
  funext node
  have left_le_right := left_least right right_closed node
  have right_le_left := right_least left left_closed node
  cases left_eq : left node <;> cases right_eq : right node <;>
    simp_all

/-- Re-running the least-solution specification cannot choose another result. -/
theorem solver_deterministic
    {graph : Graph} {candidate : Valuation graph.nodeCount}
    (candidate_closed : Closed graph candidate)
    (candidate_least :
      ∀ other, Closed graph other → PointwiseLE candidate other) :
    candidate = solve graph :=
  least_closed_unique candidate_closed (solve_closed graph) candidate_least
    (fun _ other_closed => solve_pointwise_least other_closed)

/-- A closed countermodel that is false at a node proves it unobservable. -/
theorem solve_eq_false_of_closed_false
    {graph : Graph} {candidate : Valuation graph.nodeCount}
    (candidate_closed : Closed graph candidate)
    {node : Fin graph.nodeCount}
    (candidate_false : candidate node = false) :
    solve graph node = false := by
  cases solved_eq : solve graph node with
  | false => rfl
  | true =>
      have impossible := solve_least candidate_closed solved_eq
      simp [candidate_false] at impossible

/-- With no seeds, even recursive dependency cycles remain entirely false. -/
theorem solve_eq_false_of_no_seeds
    {graph : Graph} (no_seeds : graph.seeds = [])
    (node : Fin graph.nodeCount) :
    solve graph node = false := by
  apply solve_eq_false_of_closed_false
    (candidate := fun _ => false)
  · constructor
    · intro seeded seeded_mem
      simp [no_seeds] at seeded_mem
    · intro edge edge_mem dependency_true
      simp at dependency_true
  · rfl

/-- Test whether a node is an explicit seed. -/
def seedBit (graph : Graph) (node : Fin graph.nodeCount) : Bool :=
  graph.seeds.any (fun seed => decide (seed = node))

/-- Test whether any observable dependency propagates to `node`. -/
def dependencyBit
    (graph : Graph) (valuation : Valuation graph.nodeCount)
    (node : Fin graph.nodeCount) : Bool :=
  graph.dependencies.any fun edge =>
    decide (edge.1 = node) && valuation edge.2

theorem seedBit_eq_true_iff
    {graph : Graph} {node : Fin graph.nodeCount} :
    seedBit graph node = true ↔ node ∈ graph.seeds := by
  simp [seedBit, List.any_eq_true]

theorem dependencyBit_eq_true_iff
    {graph : Graph} {valuation : Valuation graph.nodeCount}
    {node : Fin graph.nodeCount} :
    dependencyBit graph valuation node = true ↔
      ∃ dependency,
        (node, dependency) ∈ graph.dependencies ∧
          valuation dependency = true := by
  constructor
  · intro propagated
    obtain ⟨edge, edge_mem, edge_true⟩ :=
      List.any_eq_true.mp propagated
    have edge_parts : decide (edge.1 = node) = true ∧
        valuation edge.2 = true := by
      simpa only [Bool.and_eq_true] using edge_true
    rcases edge with ⟨user, dependency⟩
    have user_eq : user = node := of_decide_eq_true edge_parts.1
    subst user
    exact ⟨dependency, edge_mem, edge_parts.2⟩
  · rintro ⟨dependency, edge_mem, dependency_true⟩
    apply List.any_eq_true.mpr
    exact ⟨(node, dependency), edge_mem, by
      simp [dependency_true]⟩

/-- One conventional monotone propagation round. -/
def step
    (graph : Graph) (valuation : Valuation graph.nodeCount) :
    Valuation graph.nodeCount :=
  fun node =>
    valuation node || seedBit graph node ||
      dependencyBit graph valuation node

/-- A propagation round never clears an observable node. -/
theorem step_inflationary
    {graph : Graph} {valuation : Valuation graph.nodeCount} :
    PointwiseLE valuation (step graph valuation) := by
  intro node node_true
  simp [step, node_true]

/-- A propagation round is monotone in its input valuation. -/
theorem step_monotone
    {graph : Graph} {left right : Valuation graph.nodeCount}
    (left_le_right : PointwiseLE left right) :
    PointwiseLE (step graph left) (step graph right) := by
  intro node stepped
  simp only [step, Bool.or_eq_true] at stepped ⊢
  rcases stepped with (left_true | seeded) | propagated
  · exact Or.inl (Or.inl (left_le_right node left_true))
  · exact Or.inl (Or.inr seeded)
  · obtain ⟨dependency, edge_mem, dependency_true⟩ :=
      dependencyBit_eq_true_iff.mp propagated
    exact Or.inr <|
      dependencyBit_eq_true_iff.mpr
        ⟨dependency, edge_mem, left_le_right dependency dependency_true⟩

/-- Every seed-containing, dependency-closed valuation is a fixed point. -/
theorem step_fixed_of_closed
    {graph : Graph} {valuation : Valuation graph.nodeCount}
    (valuation_closed : Closed graph valuation) :
    step graph valuation = valuation := by
  funext node
  cases valuation_eq : valuation node with
  | true => simp [step, valuation_eq]
  | false =>
      cases seed_eq : seedBit graph node with
      | true =>
          have node_true :=
            valuation_closed.1 node (seedBit_eq_true_iff.mp seed_eq)
          simp [valuation_eq] at node_true
      | false =>
          cases propagated_eq : dependencyBit graph valuation node with
          | false => simp [step, valuation_eq, seed_eq, propagated_eq]
          | true =>
              obtain ⟨dependency, edge_mem, dependency_true⟩ :=
                dependencyBit_eq_true_iff.mp propagated_eq
              have node_true :=
                valuation_closed.2 (node, dependency) edge_mem dependency_true
              simp [valuation_eq] at node_true

/-- Every fixed point contains the seeds and is dependency-closed. -/
theorem closed_of_step_fixed
    {graph : Graph} {valuation : Valuation graph.nodeCount}
    (fixed : step graph valuation = valuation) :
    Closed graph valuation := by
  constructor
  · intro node node_seeded
    have stepped_true : step graph valuation node = true := by
      simp [step, seedBit_eq_true_iff.mpr node_seeded]
    simpa [congrFun fixed node] using stepped_true
  · intro edge edge_mem dependency_true
    have propagated_true :
        dependencyBit graph valuation edge.1 = true :=
      dependencyBit_eq_true_iff.mpr
        ⟨edge.2, edge_mem, dependency_true⟩
    have stepped_true : step graph valuation edge.1 = true := by
      simp [step, propagated_true]
    simpa [congrFun fixed edge.1] using stepped_true

theorem step_fixed_iff_closed
    {graph : Graph} {valuation : Valuation graph.nodeCount} :
    step graph valuation = valuation ↔ Closed graph valuation :=
  ⟨closed_of_step_fixed, step_fixed_of_closed⟩

/-- The computed observability mask is the least fixed point of `step`. -/
theorem solve_least_fixpoint (graph : Graph) :
    step graph (solve graph) = solve graph ∧
      ∀ candidate,
        step graph candidate = candidate →
          PointwiseLE (solve graph) candidate := by
  constructor
  · exact step_fixed_of_closed (solve_closed graph)
  · intro candidate candidate_fixed
    exact solve_pointwise_least (closed_of_step_fixed candidate_fixed)

section Examples

/--
`Rose a := node (List (Rose a))` contributes only the self-dependency
`rose.a ← rose.a`, with no seed.
-/
def roseGraph : Graph where
  nodeCount := 1
  seeds := []
  dependencies := [((0 : Fin 1), (0 : Fin 1))]

theorem rose_recursive_only_unobservable :
    solve roseGraph (0 : Fin 1) = false :=
  solve_eq_false_of_no_seeds rfl _

/--
`Tree a := leaf a | node (List (Tree a))` has the same recursive edge, but
`leaf a` supplies an explicit seed.
-/
def treeGraph : Graph where
  nodeCount := 1
  seeds := [(0 : Fin 1)]
  dependencies := [((0 : Fin 1), (0 : Fin 1))]

theorem tree_leaf_makes_parameter_observable :
    solve treeGraph (0 : Fin 1) = true :=
  solve_seed (List.mem_singleton.mpr rfl)

end Examples

end Observability
end TypePM.P2
